"use client";

import { useEffect, useMemo, useState } from "react";
import { BookMarked, ExternalLink, FileText, Filter, Link2, Pin, PinOff, Plus, Search, Sparkles, Trash2, UploadCloud } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";
import { previewPlainText } from "@/lib/text";

type Vault={id:string;title:string;item_type:"note"|"link"|"snippet"|"document";content:string|null;source_url:string|null;tags:string[];pinned:boolean;updated_at:string};
const kinds=[{v:"all",l:"Semua"},{v:"note",l:"Catatan"},{v:"link",l:"Link"},{v:"snippet",l:"Snippet"},{v:"document",l:"Dokumen"}];
export default function VaultPage(){
 const supabase=createClient();const[rows,setRows]=useState<Vault[]>([]);const[q,setQ]=useState("");const[kind,setKind]=useState("all");const[pinnedOnly,setPinnedOnly]=useState(false);const[open,setOpen]=useState(false);const[form,setForm]=useState({title:"",type:"note" as Vault["item_type"],content:"",url:"",tags:""});const[busy,setBusy]=useState(false);
 async function load(){const{data}=await supabase.from("vault_items").select("id,title,item_type,content,source_url,tags,pinned,updated_at").order("pinned",{ascending:false}).order("updated_at",{ascending:false});setRows((data as Vault[])??[])}useEffect(()=>{load()},[]);
 async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}
 async function add(){if(!form.title.trim())return;setBusy(true);await supabase.from("vault_items").insert({user_id:await uid(),title:form.title.trim(),item_type:form.type,content:form.content.trim()||null,source_url:form.url.trim()||null,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)});setForm({title:"",type:"note",content:"",url:"",tags:""});setOpen(false);setBusy(false);load()}
 async function remove(id:string){await supabase.from("vault_items").delete().eq("id",id);load()}
 async function pin(r:Vault){await supabase.from("vault_items").update({pinned:!r.pinned,updated_at:new Date().toISOString()}).eq("id",r.id);load()}
 async function importFile(file:File){setBusy(true);try{const text=await file.text();setForm(v=>({...v,title:file.name.replace(/\.[^.]+$/,""),type:"document",content:text.slice(0,50000)}));setOpen(true)}finally{setBusy(false)}}
 const visible=useMemo(()=>{const s=q.trim().toLowerCase();return rows.filter(r=>(kind==="all"||r.item_type===kind)&&(!pinnedOnly||r.pinned)&&(!s||`${r.title} ${r.content||""} ${(r.tags||[]).join(" ")} ${r.source_url||""}`.toLowerCase().includes(s)))},[rows,q,kind,pinnedOnly]);const notes=rows.filter(r=>r.item_type==="note").length;const links=rows.filter(r=>r.item_type==="link").length;const pinned=rows.filter(r=>r.pinned).length;
 return <div className="space-y-7 animate-licia-in"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><BookMarked size={14}/> PENGETAHUAN PRIBADI</p><h1 className="font-display text-3xl text-text">Licia Vault</h1><p className="mt-1 max-w-3xl text-sm leading-relaxed text-textMuted">Vault bukan gudang dump. Ia adalah perpustakaan pribadi untuk hal yang ingin ditemukan lagi, diringkas, dan menjadi konteks bagi keputusan atau percakapan berikutnya.</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border border-border bg-surface px-3.5 py-2.5 text-xs font-semibold text-textMuted hover:border-accent hover:text-accent"><UploadCloud size={15}/>{busy?"Membaca…":"Impor teks"}<input type="file" accept=".txt,.md,.csv,.json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);e.currentTarget.value=""}}/></label><PrimaryButton onClick={()=>setOpen(v=>!v)}><Plus size={16}/> Simpan</PrimaryButton></div></header>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card className="p-4"><p className="text-xs text-textMuted">Total</p><p className="mt-1 font-display text-2xl text-text">{rows.length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Catatan</p><p className="mt-1 font-display text-2xl text-accent">{notes}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Link</p><p className="mt-1 font-display text-2xl text-text">{links}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Pinned</p><p className="mt-1 font-display text-2xl text-accent">{pinned}</p></Card></div>
 <Card><div className="flex flex-col gap-3 lg:flex-row"><div className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-textMuted"/><TextInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari judul, isi, tag, atau URL…" className="pl-9"/></div><div className="flex min-w-0 gap-2 overflow-x-auto no-scrollbar"><Filter size={14} className="mt-3 shrink-0 text-textMuted"/>{kinds.map(k=><button key={k.v} onClick={()=>setKind(k.v)} className={kind===k.v?"shrink-0 rounded-lg bg-accent px-3 py-2 text-[11px] font-semibold text-white":"shrink-0 rounded-lg border border-border bg-bg px-3 py-2 text-[11px] font-semibold text-textMuted hover:text-text"}>{k.l}</button>)}<button onClick={()=>setPinnedOnly(v=>!v)} className={pinnedOnly?"shrink-0 rounded-lg bg-accent/10 px-3 py-2 text-[11px] font-semibold text-accent":"shrink-0 rounded-lg border border-border bg-bg px-3 py-2 text-[11px] font-semibold text-textMuted"}><Pin size={12} className="mr-1 inline"/>Pinned</button></div></div></Card>
 {open&&<Card><SectionTitle>Simpan pengetahuan</SectionTitle><div className="grid gap-2 sm:grid-cols-2"><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Judul"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Vault["item_type"]})} className="min-h-11 rounded-xl border border-border bg-bg px-3 text-sm text-text">{kinds.slice(1).map(k=><option key={k.v} value={k.v}>{k.l}</option>)}</select><TextInput value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="URL (opsional)"/><TextInput value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="Tag, pisahkan koma"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} rows={7} placeholder="Isi, ringkasan, atau snippet…" className="sm:col-span-2 w-full resize-none rounded-xl border border-border bg-bg px-3 py-2.5 text-sm text-text outline-none focus:ring-2 focus:ring-accent/40"/></div><div className="mt-3 flex justify-end"><PrimaryButton disabled={busy} onClick={add}>{busy?"Menyimpan…":"Simpan ke Vault"}</PrimaryButton></div></Card>}
 <SectionTitle action={<span className="text-xs text-textMuted">{visible.length} item</span>}>Pustaka pribadi</SectionTitle>
 {!visible.length?<EmptyState title="Vault masih kosong atau filter terlalu sempit" description="Simpan catatan, link, snippet, atau dokumen kecil yang sering ingin kamu temukan kembali."/>:<div className="grid gap-3 lg:grid-cols-2">{visible.map(r=><Card key={r.id} className="min-w-0 p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-accent/10 p-2 text-accent">{r.item_type==="link"?<Link2 size={17}/>:<FileText size={17}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">{r.item_type}</span>{r.pinned&&<span className="rounded-full bg-accent/10 px-2 py-1 text-[10px] text-accent">Pinned</span>}</div><p className="mt-2 break-words text-sm font-semibold text-text">{r.title}</p>{r.content&&<p className="mt-1 line-clamp-4 break-words text-xs leading-relaxed text-textMuted">{previewPlainText(r.content, 420)}</p>}{(r.tags||[]).length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{r.tags.map(tag=><span key={tag} className="rounded-full border border-border px-2 py-1 text-[10px] text-textMuted">#{tag}</span>)}</div>}{r.source_url&&<a href={r.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex max-w-full items-center gap-1 text-[11px] font-semibold text-accent"><span className="truncate">Buka sumber</span><ExternalLink size={12}/></a>}<p className="mt-3 text-[10px] text-textMuted">Diperbarui {new Date(r.updated_at).toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric"})}</p></div><div className="flex shrink-0 gap-1"><button onClick={()=>pin(r)} className="rounded-lg p-2 text-textMuted hover:text-accent" title={r.pinned?"Lepas pin":"Pin"}>{r.pinned?<PinOff size={15}/>:<Pin size={15}/>}</button><button onClick={()=>remove(r.id)} className="rounded-lg p-2 text-textMuted hover:text-danger" title="Hapus"><Trash2 size={15}/></button></div></div></Card>)}</div>}
 <Card className="border-accent/20 bg-accent/5"><div className="flex gap-3"><Sparkles size={18} className="mt-0.5 shrink-0 text-accent"/><div><p className="text-sm font-semibold text-text">Vault + AI</p><p className="mt-1 text-xs leading-relaxed text-textMuted">Chat Licia dapat diarahkan untuk mencari konteks dari Vault ketika pertanyaanmu berkaitan dengan pengetahuan pribadi. Itu membuat AI lebih berguna tanpa perlu mengirim seluruh isi Vault di setiap pesan.</p></div></div></Card>
 </div>
}
