"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, FolderKanban, Plus, Timer, Trash2 } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";

type Project={id:string;name:string;description:string|null;status:"active"|"paused"|"completed"|"archived";target_date:string|null;goal_id:string|null;area_id:string|null;updated_at?:string};type Task={id:string;title:string;status:string;due_at:string|null;project_id:string|null;estimated_minutes:number|null};type Goal={id:string;title:string};type Focus={task_id:string|null;focus_minutes:number;started_at:string};
function days(v:string|null){if(!v)return null;return Math.ceil((new Date(`${v}T23:59:59`).getTime()-Date.now())/86400000)}
export default function ProjectsPage(){const supabase=createClient();const[rows,setRows]=useState<Project[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[allTasks,setAllTasks]=useState<Task[]>([]);const[focusRows,setFocusRows]=useState<Focus[]>([]);const[goals,setGoals]=useState<Goal[]>([]);const[q,setQ]=useState("");const[open,setOpen]=useState<string|null>(null);const[form,setForm]=useState({name:"",description:"",target:"",goal_id:""});const[newTask,setNewTask]=useState<Record<string,string>>({});
 async function load(){const[{data:p},{data:t},{data:all},{data:f},{data:g}]=await Promise.all([supabase.from("projects").select("id,name,description,status,target_date,goal_id,area_id,updated_at").neq("status","archived").order("updated_at",{ascending:false}),supabase.from("tasks").select("id,title,status,due_at,project_id,estimated_minutes").neq("status","done").order("due_at",{ascending:true,nullsFirst:false}).limit(300),supabase.from("tasks").select("id,title,status,due_at,project_id,estimated_minutes").order("updated_at",{ascending:false}).limit(500),supabase.from("pomodoro_sessions").select("task_id,focus_minutes,started_at").limit(1000),supabase.from("goals").select("id,title").eq("status","active").order("updated_at",{ascending:false})]);setRows((p as Project[])||[]);setTasks((t as Task[])||[]);setAllTasks((all as Task[])||[]);setFocusRows((f as Focus[])||[]);setGoals((g as Goal[])||[])}useEffect(()=>{load()},[]);async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}async function add(){if(!form.name.trim())return;await supabase.from("projects").insert({user_id:await uid(),name:form.name.trim(),description:form.description.trim()||null,target_date:form.target||null,goal_id:form.goal_id||null,status:"active"});setForm({name:"",description:"",target:"",goal_id:""});setOpen("created");load()}async function remove(id:string){await supabase.from("projects").update({status:"archived"}).eq("id",id);load()}async function addTask(projectId:string){const title=(newTask[projectId]||"").trim();if(!title)return;await supabase.from("tasks").insert({user_id:await uid(),title,status:"todo",priority:"medium",project_id:projectId});setNewTask(x=>({...x,[projectId]:""}));load()}async function status(p:Project,s:Project["status"]){await supabase.from("projects").update({status:s,updated_at:new Date().toISOString()}).eq("id",p.id);load()}
 const visible=useMemo(()=>rows.filter(p=>!q||`${p.name} ${p.description||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <div className="space-y-7 animate-licia-in"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><FolderKanban size={14}/> BUILD WITH CONTEXT</p><h1 className="font-display text-3xl text-text">Projects</h1><p className="mt-1 max-w-3xl text-sm leading-relaxed text-textMuted">Project sekarang bukan hanya tempat menyimpan daftar. Setiap project menunjukkan tugas yang tersisa, deadline, fokus, dan hubungannya dengan target.</p></div><PrimaryButton onClick={()=>setOpen(open==="form"?null:"form")}><Plus size={16}/> Project baru</PrimaryButton></header>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Card className="p-4"><p className="text-xs text-textMuted">Aktif</p><p className="mt-1 font-display text-2xl text-accent">{rows.filter(p=>p.status==="active").length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Tugas tersisa</p><p className="mt-1 font-display text-2xl text-text">{tasks.length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Perlu perhatian</p><p className="mt-1 font-display text-2xl text-danger">{rows.filter(p=>p.status==="active"&&((days(p.target_date)??999)<0||tasks.some(t=>t.project_id===p.id&&t.due_at&&new Date(t.due_at).getTime()<Date.now()))).length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Tanpa project</p><p className="mt-1 font-display text-2xl text-danger">{tasks.filter(t=>!t.project_id).length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Target aktif</p><p className="mt-1 font-display text-2xl text-success">{goals.length}</p></Card></div>
 {open==="form"&&<Card className="border-accent/20 bg-accent/5"><SectionTitle>Project baru</SectionTitle><div className="grid gap-2 sm:grid-cols-2"><TextInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama project"/><input type="date" value={form.target} onChange={e=>setForm({...form,target:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className="sm:col-span-2 resize-none rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:ring-2 focus:ring-accent/30" placeholder="Outcome yang ingin dicapai…"/><select value={form.goal_id} onChange={e=>setForm({...form,goal_id:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"><option value="">Tanpa target</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></div><div className="mt-3 flex justify-end"><PrimaryButton onClick={add}>Buat project</PrimaryButton></div></Card>}
 <div className="flex"><TextInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari project…"/></div>
 {!visible.length?<EmptyState title="Belum ada project" description="Gunakan project untuk mengikat outcome, tugas, jadwal, dan fokus dalam satu konteks."/>:<div className="grid gap-3 lg:grid-cols-2">{visible.map(p=>{const pt=tasks.filter(t=>t.project_id===p.id);const allPt=allTasks.filter(t=>t.project_id===p.id);const donePt=allPt.filter(t=>t.status==="done").length;const taskPct=allPt.length?Math.round(donePt/allPt.length*100):0;const d=days(p.target_date);const goal=goals.find(g=>g.id===p.goal_id);const focusMinutes=focusRows.filter(f=>{const t=allPt.find(x=>x.id===f.task_id);return Boolean(t)}).reduce((sum,f)=>sum+Number(f.focus_minutes||0),0);const risk=d!==null&&d<0||pt.some(t=>t.due_at&&new Date(t.due_at).getTime()<Date.now());const stale=p.updated_at?Date.now()-new Date(p.updated_at).getTime()>5*86400000:false;const health=risk?"Perlu perhatian":stale?"Stagnan":"Sehat";const healthTone=risk?"bg-danger/10 text-danger":stale?"bg-accentSoft/10 text-accentSoft":"bg-success/10 text-success";return <Card key={p.id} className={clsx("min-w-0 p-4",p.status==="completed"&&"opacity-80")}><div className="flex items-start gap-3"><div className="rounded-xl bg-accent/10 p-2.5 text-accent"><FolderKanban size={17}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><span className="rounded-full bg-bg px-2 py-1 text-[10px] font-semibold text-textMuted">{p.status}</span>{d!==null&&<span className={clsx("rounded-full px-2 py-1 text-[10px]",d<0?"bg-danger/10 text-danger":"bg-bg text-textMuted")}>{d<0?`${Math.abs(d)} hari terlambat`:d===0?"hari ini":`H-${d}`}</span>}{goal&&<span className="rounded-full bg-success/10 px-2 py-1 text-[10px] text-success">↳ {goal.title}</span>}</div><p className="mt-2 break-words font-display text-lg text-text">{p.name}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-bg"><div className="h-full rounded-full bg-accent animate-licia-progress" style={{width:`${taskPct}%`}}/></div><p className="mt-1 text-[10px] text-textMuted">{donePt}/{allPt.length} tugas selesai · {focusMinutes} menit fokus</p>{p.description&&<p className="mt-1 break-words text-xs leading-relaxed text-textMuted">{p.description}</p>}<div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-lg bg-bg p-2"><p className="text-[10px] text-textMuted">Tugas</p><p className="text-sm font-semibold text-text">{pt.length}</p></div><div className="rounded-lg bg-bg p-2"><p className="text-[10px] text-textMuted">Fokus est.</p><p className="text-sm font-semibold text-text">{pt.reduce((s,t)=>s+(t.estimated_minutes||0),0)}m</p></div><div className="rounded-lg bg-bg p-2"><p className="text-[10px] text-textMuted">Deadline</p><p className="text-sm font-semibold text-text">{p.target_date?new Date(`${p.target_date}T12:00:00`).toLocaleDateString("id-ID",{day:"numeric",month:"short"}):"—"}</p></div></div>
 <div className="mt-3 flex items-center gap-2"><input value={newTask[p.id]||""} onChange={e=>setNewTask(x=>({...x,[p.id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")addTask(p.id)}} placeholder="Tambah tugas cepat…" className="min-w-0 flex-1 rounded-lg border border-border bg-bg px-3 py-2 text-xs text-text outline-none focus:ring-2 focus:ring-accent/30"/><button onClick={()=>addTask(p.id)} className="rounded-lg bg-accent p-2 text-white"><Plus size={14}/></button></div>
 <button onClick={()=>setOpen(open===p.id?null:p.id)} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-accent">{open===p.id?"Sembunyikan detail":"Lihat tugas"}<ArrowRight size={13}/></button>{open===p.id&&<div className="mt-3 space-y-2">{pt.length?pt.slice(0,5).map(t=><div key={t.id} className="flex items-center gap-2 rounded-lg border border-border bg-bg px-3 py-2"><CheckCircle2 size={14} className="text-success"/><span className="min-w-0 flex-1 truncate text-xs text-text">{t.title}</span>{t.estimated_minutes&&<span className="text-[10px] text-textMuted">{t.estimated_minutes}m</span>}<Link href={`/focus?task=${t.id}`} className="text-textMuted hover:text-accent"><Timer size={13}/></Link></div>):<p className="rounded-lg border border-dashed border-border p-3 text-xs text-textMuted">Project ini belum punya tugas. Tambahkan satu di atas.</p>}</div>}</div><div className="flex shrink-0 gap-1"><button onClick={()=>status(p,p.status==="active"?"paused":"active")} className="rounded-lg p-2 text-textMuted hover:text-accent" title="Jeda/aktifkan">{p.status==="active"?"Ⅱ":"▶"}</button><button onClick={()=>status(p,"completed")} className="rounded-lg p-2 text-textMuted hover:text-success" title="Tandai selesai"><CheckCircle2 size={14}/></button><button onClick={()=>remove(p.id)} className="rounded-lg p-2 text-textMuted hover:text-danger" title="Arsipkan"><Trash2 size={14}/></button></div></div></Card>})}</div>}
 </div>
}
