module.exports = {
  apps: [
    {
      name: "licia",
      script: "node_modules/next/dist/bin/next",
      args: "start --hostname 127.0.0.1",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "700M",
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      listen_timeout: 10000,
      env: { NODE_ENV: "production", PORT: 3000 },
      time: true,
    },
    {
      name: "licia-reminder-worker",
      script: "scripts/reminder-worker.mjs",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "150M",
      restart_delay: 5000,
      env: { NODE_ENV: "production" },
      time: true,
    },
  ],
};
