"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, BarChart3, BookOpen, Bell, Brain, CalendarDays, CheckSquare, Database, ChevronDown, CircleHelp, Compass, FolderKanban, HeartPulse, Inbox, Layers3, MessageCircle, Search, Settings2, Smartphone, Sparkles, History, Target, Timer, Wallet, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { clsx } from "clsx";

type GuideItem={id:string;title:string;summary:string;steps:string[];example?:string;href:string;icon:LucideIcon;category:"Mulai"|"Produktivitas"|"Personal OS"|"AI & Otomasi"};
const guide:GuideItem[]=[
 {id:"dashboard",title:"Beranda",summary:"Ringkasan keadaan Life OS: apa yang perlu diperhatikan, apa yang akan datang, dan jalur cepat ke data sumber.",steps:["Buka kartu ringkasan untuk langsung masuk ke modul sumbernya.","Gunakan bagian Prioritas dan Langkah berikutnya untuk melihat pekerjaan yang paling dekat.","Gunakan bagian Keuangan untuk saldo berjalan dan arus bulan ini.","Gunakan Semua sistem utama untuk melihat modul personal lainnya."],href:"/dashboard",icon:Layers3,category:"Mulai"},
 {id:"today",title:"Hari Ini",summary:"Ruang kerja utama untuk melihat agenda, task, fokus, dan aktivitas yang relevan dengan hari berjalan.",steps:["Gunakan bagian atas untuk memahami keadaan hari ini.","Buka task atau agenda untuk melihat detail dan mengubah sumbernya.","Mulai Focus dari task yang siap dikerjakan."],href:"/today",icon:Sparkles,category:"Mulai"},
 {id:"chat",title:"Chat Licia",summary:"Pintu AI utama untuk bertanya, mencari konteks, membuat rencana, dan menjalankan tindakan pada Life OS.",steps:["Tulis perintah dengan bahasa biasa; tidak perlu menyebut tabel atau modul teknis.","Untuk permintaan lintas data, biarkan Licia mencari context yang relevan.","Untuk perubahan penting atau massal, review tindakan sebelum menerapkannya."],example:"Tinjau agenda minggu ini dan buatkan task persiapan untuk meeting yang belum punya task.",href:"/chat",icon:MessageCircle,category:"Mulai"},
 {id:"capture",title:"Capture Studio",summary:"Tempat paling cepat memasukkan teks, suara, atau gambar sebelum menentukan bentuk akhirnya.",steps:["Tulis atau rekam sesuatu yang ingin disimpan.","Pilih tujuan capture: Inbox, Task, atau Note.","Gunakan AI triage jika belum tahu harus dimasukkan ke mana."],href:"/capture",icon:Inbox,category:"Mulai"},
 {id:"inbox",title:"Smart Inbox",summary:"Tempat menampung hal mentah yang belum dipilah menjadi task, note, event, atau bentuk lainnya.",steps:["Masukkan item tanpa perlu merapikannya terlebih dahulu.","Pilah dengan AI untuk melihat saran jenis dan hubungan.","Terapkan hasil hanya setelah memastikan context-nya benar."],href:"/inbox",icon:Inbox,category:"Mulai"},
 {id:"tasks",title:"Tugas",summary:"Daftar pekerjaan yang benar-benar perlu dilakukan, lengkap dengan status, prioritas, deadline, estimasi, dan project.",steps:["Buat task dengan kalimat tindakan yang jelas.","Tambahkan deadline, prioritas, estimasi, dan project bila relevan.","Gunakan Focus untuk mengubah task menjadi sesi kerja.","Task yang berasal dari agenda dapat tetap ditautkan dengan kalender."],example:"Buat task ‘Selesaikan laporan’ dengan prioritas tinggi dan deadline besok.",href:"/tasks",icon:CheckSquare,category:"Produktivitas"},
 {id:"calendar",title:"Kalender",summary:"Komitmen berbasis waktu: meeting, kelas, perjalanan, jadwal, dan blok kegiatan.",steps:["Buat agenda dengan tanggal dan waktu yang nyata.","Tambahkan lokasi atau deskripsi bila membantu context.","Hubungkan agenda dengan task ketika ada pekerjaan persiapan/lanjutan.","Minta Licia mengubah agenda menjadi task atau pengingat."],example:"Jadikan meeting besok sebagai task persiapan 30 menit sebelumnya.",href:"/calendar",icon:CalendarDays,category:"Produktivitas"},
 {id:"focus",title:"Fokus",summary:"Ruang eksekusi untuk mengerjakan task dalam sesi waktu yang terukur.",steps:["Pilih task yang ingin dikerjakan.","Mulai sesi fokus dan kerjakan hanya satu sasaran utama.","Sesi dicatat dan dapat menjadi bukti waktu untuk analitik dan Learning."],href:"/focus",icon:Timer,category:"Produktivitas"},
 {id:"projects",title:"Proyek",summary:"Wadah pekerjaan besar yang mengelompokkan task, target, agenda, dan konteks.",steps:["Gunakan project untuk pekerjaan yang punya banyak langkah.","Tautkan task dan target agar progress dapat dibaca sebagai satu kesatuan.","Gunakan AI untuk meninjau blocker dan langkah berikutnya."],href:"/projects",icon:FolderKanban,category:"Produktivitas"},
 {id:"goals",title:"Target",summary:"Hasil yang ingin dicapai dalam horizon yang lebih panjang.",steps:["Tentukan target dan progress saat ini.","Tambahkan milestone bila target memiliki beberapa tahapan.","Tautkan project/task agar progress memiliki bukti eksekusi."],href:"/goals",icon:Target,category:"Produktivitas"},
 {id:"planner",title:"Perencana Mingguan AI",summary:"Menyusun minggu berdasarkan task, agenda, project, target, dan kapasitas yang tersedia.",steps:["Buka planner dan mulai dari context nyata.","Tinjau susunan hasil AI sebelum menerapkannya.","Gunakan hasilnya sebagai rencana kerja, bukan jadwal yang tidak bisa diubah."],href:"/planner",icon:Sparkles,category:"Produktivitas"},
 {id:"brief",title:"Brief & Review",summary:"Ringkasan dan refleksi untuk melihat perubahan hari atau minggu.",steps:["Baca ringkasan pekerjaan, agenda, fokus, dan target.","Gunakan review untuk menemukan hal yang tertunda atau perlu disederhanakan.","Jadikan hasil review sebagai bahan planning berikutnya."],href:"/brief",icon:BookOpen,category:"Produktivitas"},
 {id:"pulse",title:"Life Pulse",summary:"Snapshot lintas modul untuk melihat kondisi Life OS secara keseluruhan.",steps:["Gunakan Pulse untuk melihat pola dan sinyal lintas data.","Klik sumber data untuk masuk ke detailnya.","Gunakan sebagai pemeriksaan cepat sebelum merencanakan hari atau minggu."],href:"/pulse",icon:BarChart3,category:"Produktivitas"},
 {id:"life-map",title:"Peta Kehidupan",summary:"Melihat hubungan antara area, project, goal, task, dan bagian hidup lainnya.",steps:["Gunakan peta untuk memahami hubungan antar bagian.","Buka node untuk masuk ke data sumber.","Perbarui relasi dari modul yang memiliki data tersebut."],href:"/life-map",icon:Compass,category:"Personal OS"},
 {id:"timeline",title:"Linimasa",summary:"Jejak aktivitas Life OS yang membantu melihat apa yang berubah dan kapan.",steps:["Gunakan filter untuk melihat rentang aktivitas tertentu.","Klik aktivitas untuk kembali ke sumbernya bila tersedia.","Gunakan linimasa sebagai audit pribadi."],href:"/timeline",icon:Layers3,category:"Personal OS"},
 {id:"analytics",title:"Analitik Pribadi",summary:"Angka dan pola dari task, fokus, goal, habit, dan aktivitas lainnya.",steps:["Pilih rentang waktu yang ingin dilihat.","Bandingkan progress dan aktivitas untuk menemukan perubahan.","Jangan hanya mengejar angka; gunakan hasilnya untuk memperbaiki sistem."],href:"/analytics",icon:BarChart3,category:"Personal OS"},
 {id:"insights",title:"Pusat Insight",summary:"Kumpulan insight yang muncul dari aktivitas dan data Life OS.",steps:["Buka insight yang muncul dari data.","Periksa sumber data di balik insight.","Gunakan insight sebagai bahan pertimbangan sebelum mengubah kebiasaan."],href:"/insights",icon:Sparkles,category:"Personal OS"},
 {id:"decisions",title:"Jurnal Keputusan",summary:"Catat keputusan, konteks, keyakinan awal, dan hasil akhirnya untuk belajar dari proses.",steps:["Tulis keputusan dan konteksnya saat masih segar.","Masukkan opsi yang dipertimbangkan bila relevan.","Gunakan review setelah beberapa waktu untuk melihat hasilnya."],href:"/decisions",icon:Layers3,category:"Personal OS"},
 {id:"learning",title:"Belajar & Keahlian",summary:"Skill tracker yang menghubungkan latihan dengan Focus, target, project, dan sumber belajar.",steps:["Tambahkan skill dan level saat ini.","Tautkan target dan sumber belajar bila tersedia.","Gunakan waktu Focus sebagai bukti latihan."],href:"/learning",icon:BookOpen,category:"Personal OS"},
 {id:"memory",title:"Memori Licia",summary:"Tempat melihat informasi yang sengaja disimpan untuk membantu context AI.",steps:["Simpan hanya hal yang memang berguna dalam jangka panjang.","Tinjau memory secara berkala.","Matikan atau hapus memory yang tidak lagi kamu inginkan."],href:"/memory",icon:Brain,category:"Personal OS"},
 {id:"vault",title:"Brankas Licia",summary:"Knowledge base pribadi untuk informasi yang ingin disimpan secara terstruktur.",steps:["Simpan item penting dengan judul yang jelas.","Gunakan kategori/type untuk membantu pencarian.","Gunakan Search atau Chat ketika ingin menemukan context di dalam Vault."],href:"/vault",icon:Layers3,category:"Personal OS"},
 {id:"reading",title:"Bacaan",summary:"Daftar bacaan, progress, sesi membaca, catatan, dan takeaways.",steps:["Tambahkan buku atau materi yang sedang dibaca.","Catat sesi dan halaman bila ingin mengukur ritme.","Simpan takeaways untuk menjadi bagian dari knowledge pribadi."],href:"/reading",icon:BookOpen,category:"Personal OS"},
 {id:"habits",title:"Rutinitas",summary:"Kebiasaan yang dipantau sebagai ritme berulang, bukan task sekali jalan.",steps:["Tambahkan kebiasaan dengan target frekuensi.","Catat check-in secara konsisten.","Gunakan analytics untuk melihat ritme dari waktu ke waktu."],href:"/habits",icon:Timer,category:"Personal OS"},
 {id:"finance",title:"Keuangan",summary:"Saldo, arus kas, transaksi, anggaran, dan dompet pribadi.",steps:["Buat dompet dengan saldo awal yang benar.","Catat pemasukan dan pengeluaran pada dompet terkait.","Gunakan ringkasan bulanan dan anggaran untuk memahami arus uang."],href:"/finance",icon:Wallet,category:"Personal OS"},
 {id:"subscriptions",title:"Langganan",summary:"Pantau biaya rutin dan tanggal billing yang berulang.",steps:["Masukkan langganan dan nilai periodiknya.","Pastikan tanggal billing akurat.","Gunakan notifikasi/automation untuk mengingat renewals."],href:"/subscriptions",icon:Timer,category:"Personal OS"},
 {id:"health",title:"Kesehatan",summary:"Check-in dan log yang berhubungan dengan kesehatan serta rutinitas tubuh.",steps:["Catat log yang memang ingin dipantau.","Gunakan ringkasan untuk melihat perubahan.","Data kesehatan dapat menjadi context hanya ketika relevan dan diizinkan."],href:"/health",icon:HeartPulse,category:"Personal OS"},
 {id:"ai-history",title:"AI Action Log",summary:"Riwayat perubahan yang benar-benar dilakukan AI, lengkap dengan batch dan undo saat tersedia.",steps:["Buka AI Action Log dari Pengaturan.","Gunakan filter untuk mencari operasi tertentu.","Gunakan Undo hanya saat snapshot dan rollback tersedia."],example:"Tinjau perubahan AI yang terjadi hari ini.",href:"/ai-history",icon:History,category:"AI & Otomasi"}, {id:"command",title:"Life Command",summary:"Command center untuk perintah natural-language yang perlu menggabungkan beberapa aksi Life OS.",steps:["Tulis tujuan akhir, bukan langkah teknis.","Tinjau perubahan yang akan dilakukan jika aksinya besar.","Gunakan undo/action history bila tersedia."],example:"Rapikan semua tugas yang sudah selesai bulan ini.",href:"/command",icon:Zap,category:"AI & Otomasi"},
 {id:"search",title:"Search",summary:"Pencarian lintas data untuk menemukan task, project, goal, notes, inbox, calendar, memory, dan lainnya.",steps:["Gunakan kata kunci atau frasa yang kamu ingat.","Klik hasil untuk membuka sumber data langsung.","Untuk pertanyaan yang membutuhkan hubungan, lanjutkan ke Chat Licia."],href:"/search",icon:Search,category:"AI & Otomasi"},
 {id:"reminders",title:"Pengingat & Notifikasi",summary:"Atur pengingat custom atau alarm yang terikat langsung ke agenda, lalu kirim melalui pusat notifikasi dan Web Push.",steps:["Buat reminder dengan tanggal dan jam spesifik.","Atur default pengingat agenda dari Pengaturan.","Aktifkan push pada perangkat dan lakukan tes.","Pastikan server menjalankan dispatcher setiap menit agar reminder tetap terkirim saat halaman tertutup."],example:"Ingatkan saya berangkat jam 11 karena saya harus ke akademik.",href:"/reminders",icon:Bell,category:"AI & Otomasi"},
 {id:"life-graph",title:"Life Graph",summary:"Peta relasi Goal, Project, dan Task untuk melihat pekerjaan sebagai satu jaringan konteks.",steps:["Buka Life Graph untuk melihat target aktif dan project yang terhubung.","Periksa task terbuka di bawah masing-masing project.","Gunakan orphan signal untuk menemukan project/task yang belum punya hubungan."],href:"/life-graph",icon:Layers3,category:"Personal OS"},
 {id:"system",title:"System Center",summary:"Pusat diagnosis Licia untuk memeriksa database, AI, push, cron reminder, dan status perangkat.",steps:["Buka System Center setelah deployment atau perubahan environment.","Pastikan database, OpenAI, Push server, dan Cron reminder sesuai kebutuhan.","Gunakan Jalankan reminder untuk pengujian manual saat sesi login masih terbuka."],href:"/system",icon:Activity,category:"AI & Otomasi"},
 {id:"automations",title:"Pusat Otomatisasi",summary:"Aturan berbasis trigger, kondisi, dan action untuk pekerjaan yang berulang.",steps:["Buat trigger yang jelas.","Tambahkan kondisi agar automation tidak terlalu agresif.","Pilih action dan uji hasilnya sebelum mengaktifkan."],href:"/automations",icon:Zap,category:"AI & Otomasi"},
 {id:"ai",title:"AI lintas Life OS",summary:"Licia dapat membaca context lintas modul, mencari detail seperlunya, dan menjalankan aksi melalui tool.",steps:["Ajukan permintaan dalam bahasa biasa.","Untuk pertanyaan luas, Licia memilih context yang relevan.","Untuk perubahan banyak data, gunakan review/confirm.","Untuk operasi batch, Licia memakai satu aksi terkontrol, bukan meminta kamu mengulang satu per satu."],example:"Hapus semua tugas yang selesai. Tampilkan dulu berapa yang akan dihapus.",href:"/chat",icon:Sparkles,category:"AI & Otomasi"},
 {id:"backup",title:"Backup & Restore",summary:"Cadangan JSON terstruktur dan restore merge untuk menjaga data tetap dapat dipindahkan tanpa menghapus data yang tidak ada di file.",steps:["Buka Pengaturan → Data.","Gunakan Backup JSON untuk membuat cadangan.","Gunakan Restore merge untuk memasukkan kembali data; proses ini tidak menghapus data lain."],example:"Buat backup Licia sebelum perubahan besar.",href:"/settings",icon:Database,category:"AI & Otomasi"}, {id:"settings",title:"Pengaturan",summary:"Tempat mengatur identitas, tampilan, AI, notifikasi, workspace, PWA, dan data.",steps:["Sesuaikan tampilan dan timezone.","Atur batas akses AI serta konfirmasi aksi massal.","Atur default task, kalender, chat, motion, dan notifikasi.","Gunakan Export Data untuk cadangan."],href:"/settings",icon:Settings2,category:"AI & Otomasi"},
 {id:"pwa",title:"PWA & Offline",summary:"Pasang Licia seperti aplikasi dan tetap gunakan capture saat koneksi terputus.",steps:["Buka Licia dari https://licia.site lalu gunakan menu Install/Tambahkan ke layar utama pada browser yang mendukung.","Saat offline, gunakan Capture untuk menampung task atau note secara lokal.","Saat koneksi kembali, antrean sinkronisasi akan diproses dan status online diperbarui."],href:"/capture",icon:Smartphone,category:"AI & Otomasi"},
 {id:"guide",title:"Panduan",summary:"Panduan ini sendiri. Cari topik atau baca alur yang sedang kamu butuhkan.",steps:["Gunakan pencarian topik.","Buka modul langsung dari tombol tindakan.","Kembali ke sini kapan pun kamu lupa alur penggunaan."],href:"/guide",icon:CircleHelp,category:"Mulai"},
];
const quickPrompts=["Bantu saya menyusun hari ini.","Tinjau kalender minggu ini dan cari agenda yang perlu persiapan.","Tinjau semua tugas saya dan cari yang sudah tidak relevan."];

export default function GuidePage(){
 const [query,setQuery]=useState(""); const [open,setOpen]=useState<string|null>("dashboard"); const [category,setCategory]=useState<GuideItem["category"]|"Semua">("Semua");
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return guide.filter(x=>(category==="Semua"||x.category===category)&&(!q||`${x.title} ${x.summary} ${x.steps.join(" ")} ${x.example??""}`.toLowerCase().includes(q)))},[query,category]);
 const counts=useMemo(()=>({all:guide.length, start:guide.filter(x=>x.category==="Mulai").length, prod:guide.filter(x=>x.category==="Produktivitas").length, personal:guide.filter(x=>x.category==="Personal OS").length, ai:guide.filter(x=>x.category==="AI & Otomasi").length}),[]);
 return <div className="guide-v25 space-y-4 animate-licia-page-in">
  <header className="guide-v25-hero relative overflow-hidden rounded-[2rem] border border-accent/15 bg-surface p-4 sm:p-6"><div className="absolute -right-14 -top-14 h-48 w-48 rounded-full bg-accent/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex min-w-0 items-start gap-3"><div className="rounded-2xl bg-accent/10 p-3 text-accent"><BookOpen size={20}/></div><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-accent">Licia Help Center</p><h1 className="mt-1 break-words font-display text-2xl text-text sm:text-3xl">Panduan yang benar-benar bisa dipakai</h1><p className="mt-1 max-w-2xl break-words text-xs leading-relaxed text-textMuted">Semua modul utama Licia dijelaskan di satu tempat. Cari fitur, ikuti langkahnya, lalu buka modulnya langsung.</p></div></div><div className="grid grid-cols-4 gap-1.5 sm:w-auto"><div className="rounded-xl border border-border bg-bg px-2.5 py-2 text-center"><p className="font-display text-lg text-text">{counts.all}</p><p className="text-[8px] text-textMuted">Topik</p></div><div className="rounded-xl border border-border bg-bg px-2.5 py-2 text-center"><p className="font-display text-lg text-text">{counts.prod}</p><p className="text-[8px] text-textMuted">Kerja</p></div><div className="rounded-xl border border-border bg-bg px-2.5 py-2 text-center"><p className="font-display text-lg text-text">{counts.personal}</p><p className="text-[8px] text-textMuted">Personal</p></div><div className="rounded-xl border border-border bg-bg px-2.5 py-2 text-center"><p className="font-display text-lg text-text">{counts.ai}</p><p className="text-[8px] text-textMuted">AI</p></div></div></div></header>
  <section className="grid gap-2 md:grid-cols-3">{quickPrompts.map((p,i)=><Link key={p} href={`/chat?prompt=${encodeURIComponent(p)}`} className="guide-v25-prompt group rounded-2xl border border-border bg-surface p-3.5"><div className="flex items-center justify-between gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-xl bg-accent/10 text-[10px] font-bold text-accent">{i+1}</span><ArrowRight size={13} className="text-textMuted transition group-hover:translate-x-1 group-hover:text-accent"/></div><p className="mt-3 break-words text-xs font-semibold text-text">{p}</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Kirim sebagai pertanyaan siap pakai.</p></Link>)}</section>
  <section className="sticky top-2 z-20 rounded-2xl border border-border bg-surface/95 p-2.5 shadow-sm backdrop-blur-xl"><div className="flex flex-col gap-2 lg:flex-row"><div className="guide-v25-search flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-border bg-bg px-3"><Search size={15} className="shrink-0 text-textMuted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari misalnya: task, kalender, finance, AI, PWA…" className="min-w-0 flex-1 bg-transparent py-2.5 text-sm text-text outline-none placeholder:text-textMuted"/>{query&&<button onClick={()=>setQuery("")} className="shrink-0 rounded-lg px-2 py-1 text-[9px] font-semibold text-textMuted hover:text-text">Hapus</button>}</div><div className="flex min-w-0 gap-1 overflow-x-auto no-scrollbar">{(["Semua","Mulai","Produktivitas","Personal OS","AI & Otomasi"] as const).map(c=><button key={c} onClick={()=>setCategory(c)} className={clsx("shrink-0 rounded-xl px-3 py-2 text-[10px] font-semibold transition",category===c?"bg-accent text-white":"border border-border bg-bg text-textMuted hover:text-text")}>{c}</button>)}</div></div></section>
  <section className="space-y-2">{filtered.map(item=>{const Icon=item.icon;const expanded=open===item.id;return <article key={item.id} className={clsx("guide-v25-item overflow-hidden rounded-2xl border border-border bg-surface",expanded&&"border-accent/20 shadow-sm")}><button onClick={()=>setOpen(expanded?null:item.id)} className="flex w-full min-w-0 items-center gap-3 p-3.5 text-left sm:p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent"><Icon size={16}/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-1.5"><span className="break-words text-xs font-semibold text-text sm:text-sm">{item.title}</span><span className="rounded-full bg-bg px-1.5 py-0.5 text-[8px] font-semibold text-textMuted">{item.category}</span></span><span className="mt-0.5 block break-words text-[10px] leading-relaxed text-textMuted">{item.summary}</span></span><ChevronDown size={16} className={clsx("shrink-0 text-textMuted transition",expanded&&"rotate-180 text-accent")}/></button>{expanded&&<div className="border-t border-border px-3.5 pb-4 pt-3.5 sm:px-4"><div className="grid gap-2 sm:grid-cols-2">{item.steps.map((step,i)=><div key={step} className="flex gap-2.5 rounded-xl bg-bg p-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/10 text-[9px] font-bold text-accent">{i+1}</span><p className="min-w-0 break-words text-[10px] leading-relaxed text-textMuted">{step}</p></div>)}</div>{item.example&&<div className="mt-3 rounded-xl border border-accent/15 bg-accent/5 p-3"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-accent">Contoh</p><p className="mt-1 break-words text-[10px] leading-relaxed text-text">“{item.example}”</p></div>}<Link href={item.href} className="mt-3 inline-flex min-h-10 items-center gap-1.5 rounded-xl bg-accent px-3 py-2 text-[10px] font-semibold text-white">Buka {item.title} <ArrowRight size={11}/></Link></div>}</article>})}{!filtered.length&&<div className="rounded-2xl border border-dashed border-border p-10 text-center"><Search size={24} className="mx-auto text-accent"/><p className="mt-2 font-display text-lg text-text">Topik tidak ditemukan</p><p className="mt-1 text-xs text-textMuted">Coba kata seperti task, agenda, AI, finance, atau memory.</p></div>}</section>
 </div>;
}
