"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, Camera, ChevronDown, Database, HeartPulse, Lightbulb, Search, Settings2, ShieldCheck, Smartphone, Sparkles, Target, Wallet } from "lucide-react";
import { clsx } from "clsx";

import { useLanguage } from "@/components/LanguageProvider";
type GuideItem = {
  id: string;
  title: string;
  summary: string;
  steps: string[];
  example?: string;
  href: string;
  icon: typeof BookOpen;
  category: "Mulai" | "Rencana" | "Personal" | "AI & Privasi" | "Sistem";
};

const guide: GuideItem[] = [
  { id:"home", title:"Beranda", summary:"Ringkasan pribadi untuk agenda, keuangan, target & proyek, dan sinyal penting.", steps:["Mulai dari kondisi hari ini sebelum membuka modul lain.","Kartu informasi membawa kamu langsung ke sumber data tanpa membuat dashboard penuh.","Gunakan Chat Licia ketika perlu bertanya atau meminta tindakan yang tidak punya tombol khusus."], href:"/dashboard", icon:Sparkles, category:"Mulai" },
  { id:"plan", title:"Rencana", summary:"Pusat aktivitas berbasis waktu: tugas, kalender, fokus, perencana, Inbox, dan pengingat.", steps:["Tugas, Kalender, Fokus, dan Pengingat mengikuti satu alur Rencana.","Prioritas dengan Licia langsung menyusun dan memperbarui prioritas dari halaman Tugas tanpa membuka Chat.","Agenda → Tugas membuat task dan menghubungkannya ke agenda; Tugas → Agenda langsung mencari slot waktu dan membuat agenda.","Perencana dan Inbox menjadi alat pendukung di dalam alur yang sama."], example:"Jadwalkan dua jam belajar besok lalu buat pengingat 30 menit sebelumnya.", href:"/plan", icon:CalendarDays, category:"Rencana" },
  { id:"goals", title:"Target & Proyek", summary:"Satu ruang untuk tujuan, proyek, progres, dan pekerjaan yang mengarah kepadanya.", steps:["Gunakan tab gabungan untuk melihat target dan proyek dalam satu konteks.","Hubungkan proyek ke target agar progres tidak terputus.","Tugas dan fokus dapat dijalankan tanpa berpindah ke workspace target yang lain."], example:"Buat target lulus kuliah lalu hubungkan proyek tugas akhir ke target itu.", href:"/goals-projects", icon:Target, category:"Rencana" },
  { id:"knowledge", title:"Knowledge & Belajar", summary:"Semua pengetahuan pribadi berada di satu tempat, termasuk catatan, memory, dokumen, bacaan, dan pembelajaran.", steps:["Catatan, memory, dokumen, bacaan, dan materi belajar dikelola dari workspace yang sama.","Gunakan pencarian workspace untuk menemukan informasi tanpa membuka halaman teknis.","Chat Licia dapat membantu mencari, merangkum, atau mengubah pengetahuan menjadi tindakan."], href:"/knowledge", icon:BookOpen, category:"Personal" },
  { id:"wellbeing", title:"Kesehatan & Rutinitas", summary:"Hub gabungan untuk kesehatan, aktivitas, tidur, nutrisi, dan rutinitas harian.", steps:["Masukkan data kesehatan di bagian yang sesuai.","Checklist rutinitas tetap mengikuti hari yang benar.","Gunakan ringkasan untuk melihat pola, bukan hanya daftar entri."], href:"/wellbeing", icon:HeartPulse, category:"Personal" },
  { id:"finance", title:"Keuangan", summary:"Transaksi, anggaran, dompet, dan langganan berada dalam satu pusat keuangan.", steps:["Catat pemasukan, pengeluaran, dan transfer saldo tanpa berpindah workspace.","Tambahkan langganan langsung dari Keuangan dan tentukan siklus serta tanggal tagihannya.","Catat pembayaran langganan sebagai pengeluaran dari workspace yang sama.","Gunakan ringkasan untuk melihat saldo, arus kas, komitmen rutin, dan kategori pengeluaran."], example:"Tambahkan langganan internet bulanan, lalu catat pembayarannya saat tagihan masuk.", href:"/finance", icon:Wallet, category:"Personal" },
  { id:"capture", title:"Tangkap", summary:"Masukkan teks atau gambar lalu biarkan Licia membantu menempatkannya di ruang kerja yang tepat.", steps:["Gunakan Tangkap untuk ide atau informasi yang ingin disimpan dengan cepat.","Gambar dapat dibaca untuk jadwal, dokumen, struk, atau informasi visual lain.","Periksa hasil sebelum menerapkan perubahan dalam jumlah besar."], example:"Ambil jadwal dari foto lalu masukkan agenda yang benar ke Kalender.", href:"/capture", icon:Camera, category:"Mulai" },
  { id:"chat", title:"Chat Licia", summary:"Tempat bercakap dan meminta bantuan yang membutuhkan konteks. Aksi yang sudah punya tombol khusus tetap dijalankan langsung di workspace masing-masing.", steps:["Gunakan Chat untuk pertanyaan, penjelasan, ide, pencarian lintas Life OS, atau permintaan yang belum punya alur khusus.","Tombol seperti Prioritas dengan Licia, Agenda → Tugas, dan Tugas → Agenda tidak membuka Chat; hasilnya langsung dikerjakan di workspace.","Perubahan massal yang berisiko akan muncul sebagai ringkasan persetujuan di dalam percakapan, bukan panel yang menumpuk.","Gunakan tombol Batalkan ketika aksi terakhir masih dapat dipulihkan."], example:"Tanya kondisi minggu ini, lalu minta Licia menjelaskan faktor yang paling memengaruhinya.", href:"/chat", icon:Sparkles, category:"AI & Privasi" },
  { id:"insights", title:"Insights", summary:"Pusat wawasan untuk review, pola, peta, aktivitas, dan otomasi.", steps:["Gunakan ringkasan untuk memahami sinyal penting terlebih dahulu.","Peta Hidup + Peta Koneksi tersedia dari satu konteks Peta & Relasi.","Linimasa + Analitik + Review dijelajahi melalui konteks Review & Pola.","Otomasi tetap tersedia dari Insights, bukan sebagai menu utama baru."], href:"/insights", icon:Lightbulb, category:"Personal" },
  { id:"system", title:"Sistem, Privasi & Perangkat", summary:"Kontrol teknis disederhanakan agar pengguna tidak perlu memilih antara banyak pusat sistem.", steps:["Pengaturan menjadi pintu utama untuk privasi AI, sinkronisasi, notifikasi, data, dan pemeriksaan sistem.","Riwayat aksi AI digunakan untuk transparansi dan undo dari operasi yang mendukung pemulihan.","Fitur yang sudah digabung tidak muncul kembali sebagai menu terpisah di ponsel maupun desktop."], href:"/settings", icon:Settings2, category:"Sistem" },
  { id:"mobile-more", title:"Lainnya di ponsel", summary:"Lainnya adalah katalog tujuan aktif di ponsel. Workspace yang sudah digabung tidak kembali muncul sebagai menu lama.", steps:["Ketuk Lainnya pada footer untuk membuka seluruh tujuan aktif.","Pilih workspace seperti Rencana, Target & Proyek, Knowledge & Belajar, Keuangan, Kesehatan & Rutinitas, atau Insights.","Pintasan gabungan seperti Kalender & Pengingat, Perencana & Inbox, Peta & Relasi, dan Review & Pola tetap menuju workspace induknya.","Menu lama seperti Target, Proyek, Langganan, Catatan, Memory, Vault, Analitik, Timeline, atau Pengingat tidak ditampilkan lagi sebagai tujuan terpisah."], href:"/dashboard", icon:Smartphone, category:"Mulai" },
  { id:"privacy", title:"Privasi AI", summary:"Tentukan bagian data mana yang boleh dibaca Licia.", steps:["Izin mengikuti workspace yang terlihat oleh pengguna.","Keuangan dan Kesehatan tetap dapat dibatasi secara terpisah.","Mode konteks luas tidak mengabaikan izin domain sensitif."], href:"/settings#ai", icon:ShieldCheck, category:"AI & Privasi" },
  { id:"settings", title:"Pengaturan", summary:"Satu tempat untuk tampilan, workspace, AI, interaksi, perangkat, notifikasi, data, dan kompatibilitas fitur gabungan.", steps:["Tampilan mengatur font, tema, ukuran, bahasa, dan halaman awal.","Workspace menjelaskan struktur canonical yang sama di desktop dan ponsel.","AI & Privasi mengatur perilaku dan izin data tanpa mengembalikan menu teknis lama.","Perangkat & Notifikasi dan Data & Akun menampung kontrol teknis yang jarang dipakai."], href:"/settings", icon:Settings2, category:"Sistem" },
  { id:"search", title:"Pencarian", summary:"Cari lintas workspace tanpa perlu mengetahui asal fitur sebelumnya.", steps:["Gunakan kata yang spesifik atau nama entitas.","Buka workspace sumber untuk melanjutkan tindakan.","Gunakan Chat hanya ketika pencarian perlu ditafsirkan atau ditindaklanjuti."], href:"/search", icon:Search, category:"Mulai" },
  { id:"backup", title:"Ekspor & Backup", summary:"Simpan salinan data pribadi untuk arsip atau pemulihan.", steps:["Buka Pengaturan → Data & Akun.","Gunakan Ekspor untuk membuat salinan.","Gunakan Backup & Restore untuk pemulihan atau pemindahan data."], href:"/settings#data", icon:Database, category:"Sistem" },
];

const quickPrompts = [
  "Apa yang paling penting hari ini?",
  "Rapikan jadwal saya besok dan cari konflik.",
  "Buat tugas dari ide ini dan beri deadline yang masuk akal.",
];

export default function GuidePage() {
  const { t: tr } = useLanguage();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState<string | null>("home");
  const [category, setCategory] = useState<GuideItem["category"] | "Semua">("Semua");
  const categories = ["Semua", "Mulai", "Rencana", "Personal", "AI & Privasi", "Sistem"] as const;
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return guide.filter((x) => (category === "Semua" || x.category === category) && (!q || `${x.title} ${tr(x.title)} ${tr(x.summary)} ${x.steps.map((st) => tr(st)).join(" ")} ${x.example ? tr(x.example) : ""}`.toLowerCase().includes(q)));
  }, [query, category]);

  return <div className="guide-shell mx-auto max-w-5xl space-y-6 animate-licia-page-in">
    <header className="guide-shell-hero relative overflow-hidden rounded-[2rem] border border-accent/15 bg-gradient-to-br from-accent/10 via-surface to-surface p-5 shadow-sm sm:p-8">
      <div className="absolute -right-14 -top-14 h-56 w-56 rounded-full bg-accent/10 blur-3xl" />
      <div className="absolute -bottom-20 left-1/3 h-48 w-48 rounded-full bg-accent/5 blur-3xl" />
      <div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
        <div className="flex min-w-0 items-start gap-4"><div className="rounded-2xl bg-accent p-3.5 text-white shadow-lg shadow-accent/20"><BookOpen size={22}/></div><div className="min-w-0"><p className="text-2xs font-bold uppercase tracking-[.16em] text-accent">{tr("Pusat Bantuan Licia")}</p><h1 className="mt-1 break-words font-display text-3xl text-text sm:text-4xl">{tr("Panduan Licia")}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-textMuted">{tr("Panduan penggunaan yang mengikuti struktur aplikasi saat ini. Tidak perlu menghafal banyak menu: mulai dari Beranda, Rencana, Chat, Tangkap, atau Insights. Fitur yang serupa sudah ditempatkan dalam workspace yang sama. Tombol Lainnya di ponsel hanya menampilkan pilihan yang masih menjadi tujuan aktif.")}</p></div></div>
        <Link href="/chat" className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl bg-accent px-4 text-sm font-semibold text-white shadow-md shadow-accent/20 transition hover:-translate-y-0.5 hover:shadow-lg"><Sparkles size={15}/> {" "}{tr("Tanya Licia")}<ArrowRight size={14}/></Link>
      </div>
    </header>

    <section aria-label={tr("Mulai dengan Licia")} className="grid gap-3 md:grid-cols-3">{quickPrompts.map((p, i) => <Link key={p} href={`/chat?prompt=${encodeURIComponent(tr(p))}`} className="guide-shell-prompt group rounded-2xl border border-border bg-surface p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-accent/30 hover:shadow-md"><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-accent/10 text-xs font-bold text-accent">{i+1}</span><ArrowRight size={15} className="text-textMuted transition group-hover:translate-x-0.5 group-hover:text-accent"/></div><p className="mt-3 text-sm font-semibold leading-relaxed text-text">{tr(p)}</p><span className="mt-2 block text-2xs font-medium text-accent">{tr("Tanya Licia")}</span></Link>)}</section>

    <section aria-label={tr("Cari panduan")} className="sticky top-2 z-20 rounded-2xl border border-border bg-surface/95 p-3 shadow-md backdrop-blur-xl"><div className="flex flex-col gap-2 lg:flex-row"><div className="guide-shell-search flex min-h-11 min-w-0 flex-1 items-center gap-2 rounded-xl border border-border bg-bg px-3"><Search size={17} className="shrink-0 text-textMuted"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={tr("Cari panduan")} placeholder={tr("Cari task, kalender, AI, pengaturan…")} className="min-w-0 flex-1 bg-transparent py-2.5 text-sm text-text outline-none placeholder:text-textMuted"/>{query&&<button onClick={()=>setQuery("")} className="rounded-lg px-2 py-1 text-2xs font-semibold text-textMuted hover:text-text">{tr("Hapus")}</button>}</div><div className="flex min-w-0 gap-1.5 overflow-x-auto no-scrollbar pb-0.5">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c} className={clsx("min-h-10 shrink-0 rounded-xl px-3.5 text-xs font-semibold transition",category===c?"bg-accent text-white shadow-sm":"border border-border bg-bg text-textMuted hover:border-accent/30 hover:text-text")}>{c}</button>)}</div></div></section>

    <section aria-label={tr("Topik panduan")} className="space-y-3">{filtered.map(item=>{const Icon=item.icon;const expanded=open===item.id;return <article key={item.id} className={clsx("overflow-hidden rounded-2xl border bg-surface transition duration-200",expanded?"border-accent/30 shadow-md shadow-accent/5":"border-border shadow-sm hover:border-accent/20 hover:shadow-md")}><button aria-expanded={expanded} onClick={()=>setOpen(expanded?null:item.id)} className="flex w-full min-w-0 items-center gap-3.5 p-4 text-left sm:p-5"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-accent/10 text-accent"><Icon size={19}/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-1.5"><span className="text-sm font-bold text-text sm:text-base">{tr(item.title)}</span><span className="rounded-full bg-bg px-1.5 py-0.5 text-2xs font-semibold text-textMuted">{tr(item.category)}</span></span><span className="mt-1 block text-xs leading-relaxed text-textMuted sm:text-sm">{tr(item.summary)}</span></span><ChevronDown size={18} className={clsx("shrink-0 text-textMuted transition",expanded&&"rotate-180 text-accent")}/></button>{expanded&&<div className="border-t border-border px-4 pb-5 pt-4 sm:px-5"><div className="grid gap-2.5 sm:grid-cols-2">{item.steps.map((step,i)=><div key={tr(step)} className="flex gap-3 rounded-xl border border-border/70 bg-bg p-3.5"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent/10 text-xs font-bold text-accent">{i+1}</span><p className="min-w-0 text-xs leading-relaxed text-textMuted sm:text-sm">{tr(step)}</p></div>)}</div>{item.example&&<div className="mt-3 rounded-xl border border-accent/15 bg-accent/5 p-4"><p className="text-2xs font-bold uppercase tracking-[.12em] text-accent">{tr("Contoh")}</p><p className="mt-1.5 text-sm leading-relaxed text-text">“{tr(item.example)}”</p></div>}<Link href={item.href} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-accent px-4 py-2 text-xs font-semibold text-white transition hover:brightness-110">{tr("Buka {item_title}", { item_title: item.title })}<ArrowRight size={14}/></Link></div>}</article>})}{!filtered.length&&<div className="rounded-2xl border border-dashed border-border bg-surface p-10 text-center"><Search size={24} className="mx-auto text-accent"/><p className="mt-2 font-display text-lg text-text">{tr("Topik tidak ditemukan")}</p><p className="mt-1 text-xs text-textMuted">{tr("Coba kata seperti task, agenda, AI, privacy, atau backup.")}</p></div>}</section>
  </div>;
}
