import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, CalendarDays, CheckCircle2, FolderKanban, Inbox, Repeat2, Target, Timer, Wallet, Waypoints } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { getOrCreateProfile } from "@/lib/getOrCreateProfile";
import { Card, SectionTitle, StatTile } from "@/components/ui";
import { startOfMonthIsoForTimezone, startOfWeekIsoForTimezone, dateStrInTimezone } from "@/lib/date";

function rupiah(n:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function pct(n:number,d:number){return d?Math.round(n/d*100):0}
function width(v:number,max:number){return `${max ? Math.max(6,Math.min(100,Math.round(v/max*100))) : 6}%`}

export default async function AnalyticsPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;
 const {data:profile}=await supabase.from("users").select("timezone").eq("id",user.id).single();const resolved=profile??await getOrCreateProfile(supabase,user.id);const timezone=(resolved as any)?.timezone??"Asia/Jakarta";
 const now=new Date();const month=startOfMonthIsoForTimezone(now,timezone);const week=startOfWeekIsoForTimezone(now,timezone);const today=dateStrInTimezone(now,timezone);
 const [tasks,focus,expenses,incomes,projects,goals,inbox,reading,movement,habits,subscriptions,schedule]=await Promise.all([
  supabase.from("tasks").select("id,status,priority,created_at,updated_at,project_id,due_at").eq("user_id",user.id).gte("updated_at",month).limit(500),
  supabase.from("pomodoro_sessions").select("focus_minutes,started_at").eq("user_id",user.id).gte("started_at",month).limit(500),
  supabase.from("expenses").select("amount,category,occurred_at").eq("user_id",user.id).gte("occurred_at",month).limit(500),
  supabase.from("incomes").select("amount,occurred_at,source").eq("user_id",user.id).gte("occurred_at",month).limit(500),
  supabase.from("projects").select("id,name,status,target_date").eq("user_id",user.id).in("status",["active","paused"]).limit(200),
  supabase.from("goals").select("id,title,status,progress,target_date").eq("user_id",user.id).limit(200),
  supabase.from("smart_inbox_items").select("id,status,created_at").eq("user_id",user.id).gte("created_at",month).limit(500),
  supabase.from("reading_sessions").select("minutes,pages_read,started_at").eq("user_id",user.id).gte("started_at",month).limit(500),
  supabase.from("movement_logs").select("duration_minutes,intensity,logged_at").eq("user_id",user.id).gte("logged_at",month).limit(500),
  supabase.from("habit_checkins").select("checkin_date,habit_id").eq("user_id",user.id).gte("checkin_date",today.slice(0,7)+"-01").limit(1000),
  supabase.from("subscriptions").select("name,amount,billing_cycle,next_billing_date,active").eq("user_id",user.id).eq("active",true).limit(200),
  supabase.from("schedule_blocks").select("id").eq("user_id",user.id).eq("block_date",today),
 ]);
 const taskRows=tasks.data??[];const done=taskRows.filter(x=>x.status==="done").length;const open=taskRows.filter(x=>x.status!=="done").length;const focusMin=(focus.data??[]).reduce((s,x)=>s+Number(x.focus_minutes),0);const spend=(expenses.data??[]).reduce((s,x)=>s+Number(x.amount),0);const income=(incomes.data??[]).reduce((s,x)=>s+Number(x.amount),0);const moveMin=(movement.data??[]).reduce((s,x)=>s+Number(x.duration_minutes),0);const readMin=(reading.data??[]).reduce((s,x)=>s+Number(x.minutes),0);const pages=(reading.data??[]).reduce((s,x)=>s+Number(x.pages_read||0),0);const inboxProcessed=(inbox.data??[]).filter(x=>x.status==="processed").length;const activeProjects=(projects.data??[]).length;const avgGoal=(goals.data??[]).filter(x=>x.status!=="completed").length?Math.round((goals.data??[]).filter(x=>x.status!=="completed").reduce((s,x)=>s+Number(x.progress||0),0)/(goals.data??[]).filter(x=>x.status!=="completed").length):0;const recurringMonthly=(subscriptions.data??[]).reduce((s,x)=>s+Number(x.amount)*(x.billing_cycle==="yearly"?1/12:1),0);
 const byCat=Object.entries((expenses.data??[]).reduce<Record<string,number>>((a,x)=>{a[x.category]=(a[x.category]||0)+Number(x.amount);return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);const maxSpend=byCat[0]?.[1]??1;
 const weekTasks=(taskRows).filter(x=>new Date(x.updated_at).getTime()>=new Date(week).getTime());const weekDone=weekTasks.filter(x=>x.status==="done").length;
 const noDue=taskRows.filter(x=>x.status!=="done"&&!x.due_at).length;const emptyProjects=(projects.data??[]).filter(p=>!taskRows.some(t=>t.project_id===p.id)).length;
 return <div className="space-y-7 animate-licia-in"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><BarChart3 size={14}/> MESIN POLA</p><h1 className="font-display text-3xl text-text">Analitik Pribadi</h1><p className="mt-1 max-w-3xl text-sm leading-relaxed text-textMuted">Satu halaman untuk membaca pola dari seluruh Life OS—eksekusi, waktu, uang, pembelajaran, kebiasaan, dan arah—tanpa mengubah semuanya menjadi skor.</p></div><Link href="/timeline" className="inline-flex items-center gap-1.5 text-xs font-semibold text-textMuted hover:text-accent">Lihat timeline <ArrowRight size={13}/></Link></header>
 <div className="grid grid-cols-2 gap-3 xl:grid-cols-6"><StatTile label="Tugas selesai" value={String(done)} hint={`${pct(done,taskRows.length)}% dari tugas aktif di bulan ini`} icon={CheckCircle2} tone="success"/><StatTile label="Fokus" value={`${focusMin} mnt`} hint="bulan ini" icon={Timer} tone="accent"/><StatTile label="Arus bersih" value={rupiah(income-spend)} hint={`Masuk ${rupiah(income)} · Keluar ${rupiah(spend)}`} icon={Wallet} tone={income>=spend?"success":"danger"}/><StatTile label="Project" value={String(activeProjects)} hint={`${emptyProjects} belum punya next action`} icon={FolderKanban}/><StatTile label="Target rata-rata" value={`${avgGoal}%`} hint="progress target aktif" icon={Target} tone="accent"/><StatTile label="Inbox diproses" value={String(inboxProcessed)} hint="item bukan lagi status baru" icon={Inbox}/></div>
 <div className="grid gap-5 lg:grid-cols-2"><Card><SectionTitle>Ritme eksekusi</SectionTitle><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Tugas selesai minggu ini</p><p className="mt-1 font-display text-2xl text-success">{weekDone}</p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Agenda hari ini</p><p className="mt-1 font-display text-2xl text-text">{schedule.data?.length??0}</p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Tugas tanpa deadline</p><p className="mt-1 font-display text-2xl text-text">{noDue}</p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Fokus rata-rata / sesi</p><p className="mt-1 font-display text-2xl text-accent">{focus.data?.length?Math.round(focusMin/focus.data.length):0}<span className="text-sm text-textMuted"> mnt</span></p></div></div></Card>
 <Card><SectionTitle>Pengetahuan & tubuh sehari-hari</SectionTitle><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-bg p-4"><BookOpen size={15} className="text-accent"/><p className="mt-2 text-xs text-textMuted">Membaca</p><p className="mt-1 font-display text-xl text-text">{readMin} mnt</p><p className="text-[10px] text-textMuted">{pages} halaman</p></div><div className="rounded-xl bg-bg p-4"><Waypoints size={15} className="text-accent"/><p className="mt-2 text-xs text-textMuted">Aktivitas harian</p><p className="mt-1 font-display text-xl text-text">{moveMin} mnt</p><p className="text-[10px] text-textMuted">catatan harian</p></div><div className="rounded-xl bg-bg p-4"><Repeat2 size={15} className="text-accent"/><p className="mt-2 text-xs text-textMuted">Check-in rutinitas</p><p className="mt-1 font-display text-xl text-text">{habits.data?.length??0}</p><p className="text-[10px] text-textMuted">bulan berjalan</p></div><div className="rounded-xl bg-bg p-4"><CalendarDays size={15} className="text-accent"/><p className="mt-2 text-xs text-textMuted">Beban recurring</p><p className="mt-1 truncate font-display text-lg text-text">{rupiah(recurringMonthly)}</p><p className="text-[10px] text-textMuted">perkiraan / bulan</p></div></div></Card></div>
 <div className="grid gap-5 lg:grid-cols-2"><Card><SectionTitle>Distribusi pengeluaran</SectionTitle>{byCat.length?<div className="space-y-3">{byCat.map(([cat,val])=><div key={cat}><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="truncate text-text">{cat}</span><span className="shrink-0 text-textMuted">{rupiah(val)}</span></div><div className="h-2 overflow-hidden rounded-full bg-bg"><div className="h-full rounded-full bg-accent transition-all" style={{width:width(val,maxSpend)}}/></div></div>)}</div>:<p className="text-sm text-textMuted">Belum ada pengeluaran bulan ini.</p>}<Link href="/finance" className="mt-4 inline-flex items-center gap-1 text-xs text-textMuted hover:text-accent">Buka Keuangan <ArrowRight size={12}/></Link></Card>
 <Card><SectionTitle>Signal untuk ditindaklanjuti</SectionTitle><div className="space-y-2">{emptyProjects>0&&<div className="rounded-xl bg-accent/5 p-3 text-xs leading-relaxed text-textMuted"><strong className="text-text">{emptyProjects} project</strong> belum punya tugas terbuka. Tambahkan satu next action.</div>}{noDue>0&&<div className="rounded-xl bg-bg p-3 text-xs leading-relaxed text-textMuted"><strong className="text-text">{noDue} tugas</strong> belum punya deadline. Abaikan jika memang fleksibel.</div>}{(inbox.data??[]).filter(x=>x.status==="open").length>0&&<div className="rounded-xl bg-bg p-3 text-xs leading-relaxed text-textMuted"><strong className="text-text">{(inbox.data??[]).filter(x=>x.status==="open").length} item Inbox</strong> masih baru dan belum diproses.</div>}{avgGoal>0&&<div className="rounded-xl bg-bg p-3 text-xs leading-relaxed text-textMuted">Progress target aktif saat ini berada di sekitar <strong className="text-text">{avgGoal}%</strong>. Buka Target untuk melihat next step.</div>}{!emptyProjects&&!noDue&&!(inbox.data??[]).some(x=>x.status==="open")&&<p className="text-sm text-textMuted">Tidak ada gap struktural yang menonjol dari data saat ini.</p>}</div></Card></div>
 <Card className="border-accent/20 bg-accent/5"><p className="text-sm font-semibold text-text">Analytics yang terintegrasi</p><p className="mt-1 text-sm leading-relaxed text-textMuted">Data diambil dari modul yang saling berhubungan: target → project → tugas → kalender → focus, sementara Inbox, Vault, Learning, Reading, Rutinitas, Finance, Subscription, dan Health memberi konteks tambahan. Tidak ada satu metrik yang dianggap sebagai “nilai hidupmu”.</p></Card>
 </div>;
}
