import Link from "next/link";
import { Activity, ArrowRight, BookOpen, Brain, CalendarDays, CheckSquare, FolderKanban, Inbox, Search as SearchIcon, Sparkles, StickyNote, Target, Timer, Wallet, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { previewPlainText } from "@/lib/text";
import { createClient } from "@/lib/supabase/server";
import { Card, EmptyState } from "@/components/ui";
import { buildCopilotContext } from "@/lib/v36/intelligence";
import { getServerT } from "@/lib/i18n-server";

type R={id:string;type:string;title:string;detail:string;href:string;icon:LucideIcon; tone:string};
const typeMeta:Record<string,{icon:LucideIcon;tone:string}>={
 Tugas:{icon:CheckSquare,tone:"bg-accent/10 text-accent"},Proyek:{icon:FolderKanban,tone:"bg-accent/10 text-accent"},Target:{icon:Target,tone:"bg-success/10 text-success"},Catatan:{icon:StickyNote,tone:"bg-accentSoft/10 text-accentSoft"},Inbox:{icon:Inbox,tone:"bg-accent/10 text-accent"},Kalender:{icon:CalendarDays,tone:"bg-accentSoft/10 text-accentSoft"},Keputusan:{icon:Activity,tone:"bg-danger/10 text-danger"},Rutinitas:{icon:Timer,tone:"bg-accent/10 text-accent"},Langganan:{icon:Wallet,tone:"bg-accentSoft/10 text-accentSoft"},Memori:{icon:Brain,tone:"bg-accent/10 text-accent"},Vault:{icon:BookOpen,tone:"bg-accent/10 text-accent"},Automation:{icon:Zap,tone:"bg-success/10 text-success"}};
export default async function SearchPage({searchParams}:{searchParams?:Promise<{q?:string|string[]}>}){
  const { t: tr, locale } = await getServerT();
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return null; const params=searchParams?await searchParams:{}; const rawQ=params.q; const q=(Array.isArray(rawQ)?rawQ[0]:rawQ||"").trim(); let results:R[]=[]; let related:any[]=[];
 if(q.length>=2){
  const profile=await supabase.from("users").select("timezone").eq("id",user.id).maybeSingle();
  const copilot=await buildCopilotContext(supabase,user.id,String(profile.data?.timezone||"Asia/Jakarta"));
  related=copilot.evidence.filter((x:any)=>`${x.label} ${x.detail} ${x.sourceType}`.toLowerCase().includes(q.toLowerCase())).slice(0,6);
  const like=`%${q.replace(/[%_]/g,"\\$&")}%`;const [tasks,projects,goals,notes,inbox,agenda,decisions,habits,subs,memory,vault,automations]=await Promise.all([
  supabase.from("tasks").select("id,title,status,due_at").eq("user_id",user.id).ilike("title",like).limit(20),
  supabase.from("projects").select("id,name,status").eq("user_id",user.id).ilike("name",like).limit(20),
  supabase.from("goals").select("id,title,status,progress").eq("user_id",user.id).ilike("title",like).limit(20),
  supabase.from("brain_dump_notes").select("id,title,content").eq("user_id",user.id).or(`title.ilike.${like},content.ilike.${like}`).limit(20),
  supabase.from("smart_inbox_items").select("id,content,status").eq("user_id",user.id).ilike("content",like).limit(20),
  supabase.from("schedule_blocks").select("id,title,block_date,start_time").eq("user_id",user.id).ilike("title",like).limit(20),
  supabase.from("decisions").select("id,title,decision,outcome").eq("user_id",user.id).or(`title.ilike.${like},decision.ilike.${like}`).limit(20),
  supabase.from("habits").select("id,name,target_per_week").eq("user_id",user.id).ilike("name",like).limit(20),
  supabase.from("subscriptions").select("id,name,active").eq("user_id",user.id).ilike("name",like).limit(20),
  supabase.from("user_memories").select("id,memory_key,memory_value").eq("user_id",user.id).or(`memory_key.ilike.${like},memory_value.ilike.${like}`).limit(20),
  supabase.from("vault_items").select("id,title,content,item_type").eq("user_id",user.id).or(`title.ilike.${like},content.ilike.${like}`).limit(20),
  supabase.from("automations").select("id,name,enabled").eq("user_id",user.id).ilike("name",like).limit(20),
 ]);
 const push=(items:any[]|null,type:string,mapper:(x:any)=>{title:string;detail:string})=>{const meta=typeMeta[type]; for(const x of items??[]){const v=mapper(x);results.push({id:String(x.id),type,title:v.title,detail:v.detail,href:type==="Tugas"?"/tasks":type==="Proyek"?"/projects":type==="Target"?"/goals":type==="Catatan"?"/notes":type==="Inbox"?"/inbox":type==="Kalender"?"/calendar":type==="Keputusan"?"/decisions":type==="Rutinitas"?"/habits":type==="Langganan"?"/subscriptions":type==="Memori"?"/memory":type==="Vault"?"/vault":"/automations",icon:meta.icon,tone:meta.tone});}};
 push(tasks.data,"Tugas",x=>({title:x.title,detail:x.status==="done"?"Selesai":x.due_at?`Tenggat ${new Date(x.due_at).toLocaleDateString(locale,{day:"numeric",month:"short"})}`:"Tanpa tenggat"}));
 push(projects.data,"Proyek",x=>({title:x.name,detail:x.status})); push(goals.data,"Target",x=>({title:x.title,detail:`${x.progress??0}% · ${x.status}`})); push(notes.data,"Catatan",x=>({title:x.title||"Tanpa judul",detail:previewPlainText(x.content,120)})); push(inbox.data,"Inbox",x=>({title:previewPlainText(x.content,100)||"Inbox",detail:x.status})); push(agenda.data,"Kalender",x=>({title:x.title,detail:`${x.block_date} · ${String(x.start_time).slice(0,5)}`})); push(decisions.data,"Keputusan",x=>({title:x.title,detail:x.outcome?tr("Sudah ditinjau"):tr("Perlu ditinjau")})); push(habits.data,"Rutinitas",x=>({title:x.name,detail:tr("target {target_per_week}/minggu", { target_per_week: x.target_per_week })})); push(subs.data,"Langganan",x=>({title:x.name,detail:x.active?"Aktif":"Nonaktif"})); push(memory.data,"Memori",x=>({title:x.memory_key,detail:previewPlainText(x.memory_value,110)})); push(vault.data,"Vault",x=>({title:x.title,detail:x.item_type})); push(automations.data,"Automation",x=>({title:x.name,detail:x.enabled?"Aktif":"Nonaktif"}));
 }
 const counts=results.reduce<Record<string,number>>((acc,r)=>(acc[r.type]=(acc[r.type]||0)+1,acc),{});
 const grouped=Object.entries(counts).sort((a,b)=>b[1]-a[1]);
 return <div className="search-v24 space-y-3 animate-licia-page-in">
  <header className="rounded-[1.65rem] border border-accent/15 bg-surface p-4 sm:p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-accent/10 p-3 text-accent"><SearchIcon size={19}/></div><div className="min-w-0"><p className="text-2xs font-bold uppercase tracking-[.15em] text-accent">{tr("Universal Search")}</p><h1 className="mt-1 break-words font-display text-2xl text-text sm:text-3xl">{tr("Temukan apa pun")}</h1><p className="mt-1 text-xs leading-relaxed text-textMuted">{tr("Cari lintas tugas, kalender, project, catatan, Inbox, memory, vault, dan data lain.")}</p></div></div>
   <form method="get" action="/search" className="mt-4"><div className="search-v24-form"><SearchIcon size={15} className="shrink-0 text-textMuted"/><input name="q" defaultValue={q} autoComplete="off" placeholder={tr("Ketik sesuatu yang kamu ingat…")} className="min-w-0 flex-1 bg-transparent text-sm text-text outline-none placeholder:text-textMuted"/><button type="submit" className="shrink-0 rounded-xl bg-accent px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:-translate-y-0.5">{tr("Cari")}</button></div></form>
  </header>
  {!q&&<section className="grid gap-2 sm:grid-cols-3"><Link href="/search?q=tugas" className="group rounded-2xl border border-border bg-surface p-4"><CheckSquare size={17} className="text-accent"/><p className="mt-3 text-xs font-semibold text-text">{tr("Tugas")}</p><p className="mt-1 text-2xs leading-relaxed text-textMuted">{tr("Temukan pekerjaan berdasarkan judul.")}</p><ArrowRight size={12} className="mt-3 text-textMuted transition group-hover:translate-x-1"/></Link><Link href="/search?q=meeting" className="group rounded-2xl border border-border bg-surface p-4"><CalendarDays size={17} className="text-accentSoft"/><p className="mt-3 text-xs font-semibold text-text">{tr("Agenda")}</p><p className="mt-1 text-2xs leading-relaxed text-textMuted">{tr("Cari rapat, acara, atau jadwal yang pernah dicatat.")}</p><ArrowRight size={12} className="mt-3 text-textMuted transition group-hover:translate-x-1"/></Link><Link href="/search?q=project" className="group rounded-2xl border border-border bg-surface p-4"><Sparkles size={17} className="text-success"/><p className="mt-3 text-xs font-semibold text-text">{tr("Konteks")}</p><p className="mt-1 text-2xs leading-relaxed text-textMuted">{tr("Lihat keterhubungan data dari seluruh Life OS.")}</p><ArrowRight size={12} className="mt-3 text-textMuted transition group-hover:translate-x-1"/></Link></section>}
  {q&&<section className="rounded-2xl border border-border bg-surface p-3"><div className="flex flex-wrap items-center gap-2"><span className="text-2xs font-bold uppercase tracking-[.14em] text-textMuted">{tr("{results_length} hasil", { results_length: results.length })}</span>{grouped.map(([type,count])=><span key={type} className="rounded-full border border-border bg-bg px-2.5 py-1.5 text-2xs font-semibold text-textMuted">{type} · {count}</span>)}</div></section>}
  {q&&related.length>0&&<section className="rounded-2xl border border-accent/15 bg-accent/5 p-4"><div className="flex items-center gap-2"><Sparkles size={14} className="text-accent"/><p className="text-xs font-semibold text-text">{tr("Konteks yang mungkin terkait")}</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{related.map((x:any,i:number)=><Link key={`${x.sourceType}-${x.sourceId||i}`} href={x.href||"/insights"} className="rounded-xl bg-surface p-3 transition hover:border-accent/30 border border-border"><p className="text-xs font-semibold text-text">{x.label}</p><p className="mt-1 text-2xs leading-relaxed text-textMuted">{x.detail}</p></Link>)}</div><Link href={`/chat?prompt=${encodeURIComponent(tr("Jelaskan hubungan data yang terkait dengan {q} dan tunjukkan evidence-nya.", { q }))}`} className="mt-3 inline-flex items-center gap-1 text-2xs font-semibold text-accent">{tr("Tanya Licia tentang konteks ini")}{" "}<ArrowRight size={11}/></Link></section>}
  {q&&!results.length?<EmptyState title={tr("Belum ditemukan")} description={tr("Tidak ada data yang cocok dengan “{q}”. Coba kata lain atau gunakan Search untuk membuka konteks yang lebih umum.", { q })}/>:q&&results.length>0&&<section className="space-y-2">{results.map((r,i)=><Link key={`${r.type}-${r.id}`} href={r.href} className="search-v24-result group flex min-w-0 items-center gap-3 rounded-2xl border border-border bg-surface p-3.5 transition hover:-translate-y-0.5 hover:border-accent/25 hover:shadow-sm"><span className={`shrink-0 rounded-xl p-2.5 ${r.tone}`}><r.icon size={16}/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-1.5"><b className="break-words text-xs text-text sm:text-sm">{r.title}</b><span className="rounded-full bg-bg px-1.5 py-0.5 text-2xs font-semibold text-textMuted">{r.type}</span></span><span className="mt-1 block break-words text-2xs leading-relaxed text-textMuted">{r.detail}</span></span><ArrowRight size={14} className="shrink-0 text-textMuted transition group-hover:translate-x-1 group-hover:text-accent"/></Link>)}</section>}
  {q&&results.length>0&&<div className="flex items-center justify-between gap-2 rounded-2xl border border-dashed border-border px-4 py-3 text-2xs text-textMuted"><span>{tr("Cari dengan bahasa biasa juga bisa. Untuk hubungan lintas modul, gunakan Chat Licia.")}</span><Link href={`/chat?prompt=${encodeURIComponent(tr("Cari dan jelaskan semua data yang berkaitan dengan {q}.", { q }))}`} className="inline-flex shrink-0 items-center gap-1 font-semibold text-accent">{tr("Tanya Licia")}{" "}<ArrowRight size={11}/></Link></div>}
 </div>;
}
