"use client";

import { useEffect, useMemo, useState } from "react";
import { Brain, Check, Eye, EyeOff, Filter, Lightbulb, Plus, Search, ShieldCheck, Trash2 } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";

type Memory={id:string;category:string;memory_key:string;memory_value:string;source:string|null;enabled:boolean;updated_at:string};
const cats=["Semua","Preferensi","Konteks","Rutinitas","Belajar","Proyek","Kecerdasan"];const catValue:Record<string,string>={Preferensi:"preferensi",Konteks:"konteks",Rutinitas:"rutinitas",Belajar:"learning",Proyek:"project",Kecerdasan:"ai"};
export default function MemoryPage(){
 const supabase=createClient();const[rows,setRows]=useState<Memory[]>([]);const[open,setOpen]=useState(false);const[q,setQ]=useState("");const[filter,setFilter]=useState("Semua");const[form,setForm]=useState({category:"preferensi",key:"",value:""});const[busy,setBusy]=useState(false);
 async function load(){const{data}=await supabase.from("user_memories").select("id,category,memory_key,memory_value,source,enabled,updated_at").order("updated_at",{ascending:false});setRows((data as Memory[])??[])}useEffect(()=>{load()},[]);
 async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}
 async function add(){if(!form.key.trim()||!form.value.trim())return;setBusy(true);await supabase.from("user_memories").insert({user_id:await uid(),category:form.category,memory_key:form.key.trim(),memory_value:form.value.trim(),source:"manual"});setForm({category:"preferensi",key:"",value:""});setOpen(false);setBusy(false);load()}
 async function toggle(r:Memory){await supabase.from("user_memories").update({enabled:!r.enabled,updated_at:new Date().toISOString()}).eq("id",r.id);load()}
 async function remove(id:string){await supabase.from("user_memories").delete().eq("id",id);load()}
 const visible=useMemo(()=>{const s=q.trim().toLowerCase();return rows.filter(r=>(filter==="Semua"||r.category===catValue[filter])&&(!s||`${r.memory_key} ${r.memory_value} ${r.category} ${r.source||""}`.toLowerCase().includes(s)))},[rows,q,filter]);const enabled=rows.filter(r=>r.enabled).length;const auto=rows.filter(r=>r.source&&r.source!=="manual").length;
 return <div className="space-y-7 animate-licia-in"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><Brain size={14}/> MEMORY ENGINE</p><h1 className="font-display text-3xl text-text">Memory Licia</h1><p className="mt-1 max-w-3xl text-sm leading-relaxed text-textMuted">Memory adalah lapisan konteks jangka panjang. Licia hanya seharusnya mengingat hal yang stabil dan membantu, bukan menyalin seluruh percakapan.</p></div><PrimaryButton onClick={()=>setOpen(v=>!v)}><Plus size={16}/> Memory baru</PrimaryButton></header>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card className="p-4"><p className="text-xs text-textMuted">Memory aktif</p><p className="mt-1 font-display text-2xl text-accent">{enabled}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Total tersimpan</p><p className="mt-1 font-display text-2xl text-text">{rows.length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Ditangkap Kecerdasan</p><p className="mt-1 font-display text-2xl text-text">{auto}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Dipakai chat</p><p className="mt-1 font-display text-2xl text-success">Aktif</p></Card></div>
 <Card className="border-success/20 bg-success/5"><div className="flex gap-3"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-success"/><div><p className="text-sm font-semibold text-text">Kontrol tetap di tanganmu</p><p className="mt-1 text-xs leading-relaxed text-textMuted">Memory aktif dapat dipakai saat konteks percakapan relevan. Kamu bisa menonaktifkan memory tanpa menghapusnya, atau menghapusnya permanen.</p></div></div></Card>
 {open&&<Card><SectionTitle>Tambah memory yang bisa dipakai Licia</SectionTitle><div className="grid gap-2 sm:grid-cols-[180px_1fr]"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="min-h-11 rounded-xl border border-border bg-bg px-3 text-sm text-text">{cats.slice(1,-1).map(c=><option key={c} value={catValue[c]}>{c}</option>)}</select><TextInput value={form.key} onChange={e=>setForm({...form,key:e.target.value})} placeholder="Kunci · contoh: editor_favorit"/><textarea value={form.value} onChange={e=>setForm({...form,value:e.target.value})} placeholder="Nilai · tulis satu fakta yang stabil dan bermanfaat." rows={3} className="sm:col-span-2 w-full resize-none rounded-xl border border-border bg-bg px-3 py-2.5 text-sm text-text outline-none focus:ring-2 focus:ring-accent/40"/></div><div className="mt-3 flex justify-end"><PrimaryButton onClick={add} disabled={busy}><Check size={15}/> {busy?"Menyimpan…":"Simpan memory"}</PrimaryButton></div></Card>}
 <Card><div className="flex flex-col gap-3 sm:flex-row"><div className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-textMuted"/><TextInput value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari memory…" className="pl-9"/></div><div className="flex min-w-0 items-center gap-2 overflow-x-auto no-scrollbar"><Filter size={14} className="shrink-0 text-textMuted"/>{cats.map(c=><button key={c} onClick={()=>setFilter(c)} className={filter===c?"shrink-0 rounded-lg bg-accent px-3 py-2 text-[11px] font-semibold text-white":"shrink-0 rounded-lg border border-border bg-bg px-3 py-2 text-[11px] font-semibold text-textMuted hover:text-text"}>{c}</button>)}</div></div></Card>
 <SectionTitle action={<span className="text-xs font-medium text-textMuted">{visible.length} terlihat</span>}>Memory yang tersedia</SectionTitle>
 {!visible.length?<EmptyState title="Memory tidak ditemukan" description="Coba kata kunci lain atau buat memory baru yang lebih spesifik."/>:<div className="grid gap-3 md:grid-cols-2">{visible.map(r=><Card key={r.id} className={clsx("min-w-0 p-4",!r.enabled&&"opacity-60")}><div className="flex items-start gap-3"><div className="rounded-xl bg-accent/10 p-2 text-accent"><Brain size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5"><span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">{r.category}</span>{r.source&&r.source!=="manual"&&<span className="rounded-full bg-accent/10 px-2 py-1 text-[10px] text-accent">Kecerdasan</span>}{!r.enabled&&<span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">Nonaktif</span>}</div><p className="mt-2 break-words text-[11px] font-semibold uppercase tracking-wider text-textMuted">{r.memory_key}</p><p className="mt-1 break-words text-sm leading-relaxed text-text">{r.memory_value}</p><p className="mt-2 text-[10px] text-textMuted">Diubah {new Date(r.updated_at).toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric"})}</p></div><div className="flex shrink-0 gap-1"><button onClick={()=>toggle(r)} className="rounded-lg p-2 text-textMuted hover:text-accent" title={r.enabled?"Matikan":"Aktifkan"}>{r.enabled?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>remove(r.id)} className="rounded-lg p-2 text-textMuted hover:text-danger" title="Hapus"><Trash2 size={15}/></button></div></div></Card>)}</div>}
 <Card className="border-accent/20 bg-accent/5"><div className="flex gap-3"><Lightbulb size={18} className="mt-0.5 shrink-0 text-accent"/><div><p className="text-sm font-semibold text-text">Apa yang sebaiknya disimpan?</p><p className="mt-1 text-xs leading-relaxed text-textMuted">Preferensi stabil, cara kerja favorit, project yang berulang, gaya belajar, atau konteks yang sering harus dijelaskan ulang. Detail sekali pakai, rahasia, atau isi percakapan mentah sebaiknya tidak dijadikan memory.</p></div></div></Card>
 </div>
}
