"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Activity, BellRing, Bot, Check, Database, Download, MonitorCog, Palette, RotateCcw, Save, Search, ShieldCheck, Smartphone, Sparkles, SlidersHorizontal, UserRound, WandSparkles, X } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, PrimaryButton, SoftButton, TextInput, notifyToast } from "@/components/ui";
import { PushNotificationControl } from "@/components/settings/PushNotificationControl";
import { ThemeToggle } from "@/components/layout/ThemeToggle";
import { MobileAccountAction } from "@/components/layout/MobileAccountAction";
import { TIMEZONE_OPTIONS } from "@/lib/date";
import { accentPresets, applyAccent, applyBackground, applyFont, BG_DEFAULT_DARK, BG_DEFAULT_LIGHT, bgPresetsDark, bgPresetsLight, fontPresets, getStoredFont, ACCENT_STORAGE_KEY, BG_DARK_STORAGE_KEY, BG_LIGHT_STORAGE_KEY, FONT_DEFAULT } from "@/lib/theme";
import { DataExportButton } from "@/components/settings/DataExportButton";
import { DataBackupButton } from "@/components/settings/DataBackupButton";

type Preferences={startPage:string;weekStart:string;density:string;reducedMotion:boolean;compactSidebar:boolean;showQuickSearchMobile:boolean;motionIntensity:string;showDailyIntelligence:boolean;browserNotifications:boolean;confirmDelete:boolean;confirmBulkActions:boolean;defaultPriority:string;defaultTaskMinutes:number;chatEnterToSend:boolean;taskView:string;taskSort:string;calendarView:string;chatStyle:string;textScale:string;pageAnimations:boolean;smartSuggestions:boolean;showHelpTips:boolean;dashboardMode:string;defaultAiMode:string;notificationPollMinutes:number;notificationLeadDays:number;aiResponseStyle:string;aiReadAllData:boolean;aiAutoLink:boolean;aiProactive:boolean;aiSuggestActions:boolean;aiConfirmDestructive:boolean;aiConfirmMassive:boolean;haptics:boolean;soundFeedback:boolean;offlineCapture:boolean;showFocusWidget:boolean;showFinanceWidget:boolean;showGoalWidget:boolean;showCalendarWidget:boolean;defaultReminderMinutes:number;dailyBriefHour:number;weeklyReviewDay:string;autoCompleteFocus:boolean;showNextMove:boolean;showModuleRail:boolean};
const DEFAULT_PREFS:Preferences={startPage:"dashboard",weekStart:"monday",density:"comfortable",reducedMotion:false,compactSidebar:false,showQuickSearchMobile:true,motionIntensity:"full",showDailyIntelligence:true,browserNotifications:false,confirmDelete:true,confirmBulkActions:true,defaultPriority:"medium",defaultTaskMinutes:25,chatEnterToSend:true,taskView:"list",taskSort:"next",calendarView:"day",chatStyle:"soft",textScale:"normal",pageAnimations:true,smartSuggestions:true,showHelpTips:true,dashboardMode:"balanced",defaultAiMode:"assistant",notificationPollMinutes:1,notificationLeadDays:7,aiResponseStyle:"normal",aiReadAllData:true,aiAutoLink:true,aiProactive:true,aiSuggestActions:true,aiConfirmDestructive:true,aiConfirmMassive:true,haptics:true,soundFeedback:false,offlineCapture:true,showFocusWidget:true,showFinanceWidget:true,showGoalWidget:true,showCalendarWidget:true,defaultReminderMinutes:15,dailyBriefHour:8,weeklyReviewDay:"sunday",autoCompleteFocus:false,showNextMove:true,showModuleRail:true};

type SectionId="appearance"|"ai"|"workspace"|"experience"|"data";
const sections:{id:SectionId;label:string;hint:string;icon:typeof MonitorCog}[]=[
  {id:"appearance",label:"Tampilan",hint:"Identitas, tema, aksen, font",icon:Palette},
  {id:"ai",label:"AI",hint:"Context engine & tindakan",icon:WandSparkles},
  {id:"workspace",label:"Workspace",hint:"Alur kerja dan default",icon:SlidersHorizontal},
  {id:"experience",label:"Pengalaman",hint:"Motion, PWA, notifikasi",icon:Smartphone},
  {id:"data",label:"Data",hint:"Backup, export, sesi",icon:ShieldCheck},
];
type BooleanPreference="reducedMotion"|"compactSidebar"|"showQuickSearchMobile"|"browserNotifications"|"confirmDelete"|"confirmBulkActions"|"chatEnterToSend"|"pageAnimations"|"smartSuggestions"|"showHelpTips"|"haptics"|"soundFeedback"|"offlineCapture"|"showFocusWidget"|"showFinanceWidget"|"showGoalWidget"|"showCalendarWidget"|"autoCompleteFocus"|"showNextMove"|"showModuleRail"|"showDailyIntelligence"|"aiReadAllData"|"aiAutoLink"|"aiProactive"|"aiSuggestActions"|"aiConfirmDestructive"|"aiConfirmMassive";

function Field({label,description,children}:{label:string;description?:string;children:ReactNode}){return <label className="block min-w-0"><span className="text-[10px] font-bold uppercase tracking-[.08em] text-textMuted">{label}</span>{children}{description&&<span className="mt-1 block text-[9px] leading-relaxed text-textMuted">{description}</span>}</label>}
function Toggle({label,hint,checked,onChange}:{label:string;hint?:string;checked:boolean;onChange:()=>void}){return <button type="button" onClick={onChange} className={clsx("settings-v27-toggle flex min-w-0 items-center justify-between gap-3 rounded-2xl border p-3 text-left",checked?"border-accent/25 bg-accent/5":"border-border bg-bg hover:border-accent/15")}><span className="min-w-0 flex-1"><span className="block break-words text-xs font-semibold text-text">{label}</span>{hint&&<span className="mt-1 block break-words text-[10px] leading-relaxed text-textMuted">{hint}</span>}</span><span className={clsx("relative h-6 w-11 shrink-0 rounded-full p-0.5 transition",checked?"bg-accent":"bg-border")}><span className={clsx("block h-5 w-5 rounded-full bg-white shadow-sm transition",checked?"translate-x-5":"translate-x-0")}/></span></button>}
function Choice({active,title,detail,onClick}:{active:boolean;title:string;detail:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={clsx("settings-v27-choice rounded-2xl border p-3 text-left transition",active?"border-accent/30 bg-accent/5 shadow-sm":"border-border bg-bg hover:border-accent/20")}><span className="block text-xs font-semibold text-text">{title}</span><span className="mt-1 block break-words text-[9px] leading-relaxed text-textMuted">{detail}</span></button>}

export default function SettingsPage(){
  const supabase=createClient();
  const [name,setName]=useState(""); const [timezone,setTimezone]=useState("Asia/Jakarta"); const [prefs,setPrefs]=useState<Preferences>(DEFAULT_PREFS);
  const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [accent,setAccent]=useState("#3d5fd9"); const [font,setFont]=useState(FONT_DEFAULT); const [background,setBackground]=useState("#eef1f7"); const [health,setHealth]=useState<any>(null); const [healthBusy,setHealthBusy]=useState(false); const [query,setQuery]=useState(""); const [activeSection,setActiveSection]=useState<SectionId>("appearance"); const [dark,setDark]=useState(false);

  useEffect(()=>{
    (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from("users").select("display_name,timezone,preferences").eq("id",user.id).single();setName(data?.display_name||"");setTimezone(data?.timezone||"Asia/Jakarta");const merged={...DEFAULT_PREFS,...((data as any)?.preferences||{})} as Preferences;setPrefs(merged);applyPrefs(merged);})();
    const refreshTheme=()=>{try{const isDark=document.documentElement.classList.contains("dark");setDark(isDark);setAccent(localStorage.getItem(ACCENT_STORAGE_KEY)||"#3d5fd9");setFont(getStoredFont());setBackground(localStorage.getItem(isDark?BG_DARK_STORAGE_KEY:BG_LIGHT_STORAGE_KEY)||(isDark?BG_DEFAULT_DARK:BG_DEFAULT_LIGHT));}catch{}};
    refreshTheme();window.addEventListener("licia:theme-change",refreshTheme as EventListener);return()=>window.removeEventListener("licia:theme-change",refreshTheme as EventListener);
  },[]);

  function applyPrefs(next:Preferences){document.documentElement.dataset.density=next.density;document.documentElement.dataset.reducedMotion=next.reducedMotion?"true":"false";document.documentElement.dataset.motion=next.motionIntensity;document.documentElement.dataset.quickSearchMobile=next.showQuickSearchMobile?"true":"false";document.documentElement.dataset.chatStyle=next.chatStyle;document.documentElement.dataset.textScale=next.textScale;document.documentElement.dataset.pageAnimations=next.pageAnimations?"true":"false";document.documentElement.dataset.showNextMove=next.showNextMove?"true":"false";document.documentElement.dataset.showModuleRail=next.showModuleRail?"true":"false";try{localStorage.setItem("licia-show-daily-intelligence",String(next.showDailyIntelligence));localStorage.setItem("licia-smart-suggestions",String(next.smartSuggestions));}catch{}}
  function update<K extends keyof Preferences>(key:K,value:Preferences[K]){const next={...prefs,[key]:value} as Preferences;setPrefs(next);applyPrefs(next);setSaved(false)}
  function toggle(key:BooleanPreference){update(key,!prefs[key]);}
  async function save(){setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk.");const {error}=await supabase.from("users").upsert({id:user.id,display_name:name.trim(),timezone,preferences:prefs});if(error)throw new Error(error.message);
    const entries:[string,string][]=[['licia-density',prefs.density],['licia-reduced-motion',String(prefs.reducedMotion)],['licia-quick-search-mobile',String(prefs.showQuickSearchMobile)],['licia-motion-intensity',prefs.motionIntensity],['licia-show-daily-intelligence',String(prefs.showDailyIntelligence)],['licia-browser-notifications',String(prefs.browserNotifications)],['licia-default-priority',prefs.defaultPriority],['licia-default-task-minutes',String(prefs.defaultTaskMinutes)],['licia-chat-enter-to-send',String(prefs.chatEnterToSend)],['licia-task-view',prefs.taskView],['licia-task-sort',prefs.taskSort],['licia-calendar-view',prefs.calendarView],['licia-chat-style',prefs.chatStyle],['licia-text-scale',prefs.textScale],['licia-page-animations',String(prefs.pageAnimations)],['licia-smart-suggestions',String(prefs.smartSuggestions)],['licia-default-ai-mode',prefs.defaultAiMode],['licia-notification-poll-minutes',String(prefs.notificationPollMinutes)],['licia-notification-lead-days',String(prefs.notificationLeadDays)],['licia-confirm-bulk-actions',String(prefs.confirmBulkActions)],['licia-ai-response-style',prefs.aiResponseStyle],['licia-ai-read-all-data',String(prefs.aiReadAllData)],['licia-ai-auto-link',String(prefs.aiAutoLink)],['licia-ai-proactive',String(prefs.aiProactive)],['licia-ai-suggest-actions',String(prefs.aiSuggestActions)],['licia-ai-confirm-destructive',String(prefs.aiConfirmDestructive)],['licia-ai-confirm-massive',String(prefs.aiConfirmMassive)],['licia-haptics',String(prefs.haptics)],['licia-sound-feedback',String(prefs.soundFeedback)],['licia-offline-capture',String(prefs.offlineCapture)],['licia-show-focus-widget',String(prefs.showFocusWidget)],['licia-show-finance-widget',String(prefs.showFinanceWidget)],['licia-show-goal-widget',String(prefs.showGoalWidget)],['licia-show-calendar-widget',String(prefs.showCalendarWidget)],['licia-default-reminder-minutes',String(prefs.defaultReminderMinutes)],['licia-daily-brief-hour',String(prefs.dailyBriefHour)],['licia-weekly-review-day',prefs.weeklyReviewDay],['licia-auto-complete-focus',String(prefs.autoCompleteFocus)],['licia-show-next-move',String(prefs.showNextMove)],['licia-show-module-rail',String(prefs.showModuleRail)]];
    try{entries.forEach(([k,v])=>localStorage.setItem(k,v));window.dispatchEvent(new CustomEvent("licia:preferences-change"));}catch{}
    setSaved(true);notifyToast({title:"Pengaturan tersimpan",message:"Preferensi Licia sudah diperbarui.",tone:"success"});setTimeout(()=>setSaved(false),2400);
  }catch(error){notifyToast({title:"Gagal menyimpan",message:error instanceof Error?error.message:"Coba lagi.",tone:"error"})}finally{setSaving(false)}}
  async function checkHealth(){setHealthBusy(true);try{const res=await fetch("/api/health",{cache:"no-store"});const data=await res.json().catch(()=>({}));setHealth(data)}catch(error){setHealth({ok:false,database:false,user:false,error:error instanceof Error?error.message:"Tidak dapat terhubung"})}finally{setHealthBusy(false)}}

  const filteredSections=sections.filter(s=>{const q=query.trim().toLowerCase();return !q||`${s.label} ${s.hint}`.toLowerCase().includes(q)});
  const selectedSection=filteredSections.some(s=>s.id===activeSection)?activeSection:(filteredSections[0]?.id||"appearance");
  const showSettings=filteredSections.length>0;
  function selectSection(id:SectionId){setActiveSection(id);window.scrollTo({top:0,behavior:"smooth"});}

  return <div className="settings-v27 space-y-5 animate-licia-page-in">
    <header className="settings-v27-hero relative overflow-hidden rounded-[2rem] border border-accent/15 bg-surface p-5 shadow-sm sm:p-7"><div className="absolute -right-24 -top-20 h-64 w-64 rounded-full bg-accent/10 blur-3xl"/><div className="relative"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><MonitorCog size={21}/></span><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-accent">Control Center</p><h1 className="mt-1 break-words font-display text-3xl text-text sm:text-4xl">Pengaturan yang rapi.</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-textMuted">Pilih satu area, fokus pada pengaturannya, lalu simpan. Tidak ada panel sticky yang menutupi form lain ketika halaman digulir.</p></div></div><div className="flex flex-col gap-2 sm:flex-row"><MobileAccountAction/><PrimaryButton onClick={save} disabled={saving}>{saving?<Sparkles size={14} className="animate-spin"/>:saved?<Check size={14}/>:<Save size={14}/>} {saved?"Tersimpan":"Simpan perubahan"}</PrimaryButton></div></div>
      <div className="mt-5 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-bg/70 p-3"><p className="text-[9px] uppercase tracking-wider text-textMuted">Mode aktif</p><p className="mt-1 text-sm font-semibold text-text">{dark?"Dark":"Light"} · {prefs.density}</p></div><div className="rounded-2xl border border-border bg-bg/70 p-3"><p className="text-[9px] uppercase tracking-wider text-textMuted">AI</p><p className="mt-1 text-sm font-semibold text-text">{prefs.defaultAiMode} · konteks {prefs.aiReadAllData?"lintas modul":"terbatas"}</p></div><div className="rounded-2xl border border-border bg-bg/70 p-3"><p className="text-[9px] uppercase tracking-wider text-textMuted">Perlindungan</p><p className="mt-1 text-sm font-semibold text-text">{prefs.confirmDelete&&(prefs.confirmBulkActions||prefs.aiConfirmMassive)?"Konfirmasi aktif":"Sebagian terbuka"}</p></div></div>
    </div></header>

    <section className="settings-v27-switcher rounded-[1.5rem] border border-border bg-surface p-3 shadow-sm"><div className="flex flex-col gap-3"><div className="flex min-w-0 items-center gap-2 rounded-xl border border-border bg-bg px-3"><Search size={14} className="shrink-0 text-textMuted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari area pengaturan…" className="min-w-0 flex-1 bg-transparent py-2.5 text-xs text-text outline-none"/>{query&&<button type="button" onClick={()=>setQuery("")} className="touch-target shrink-0 text-textMuted" aria-label="Hapus pencarian"><X size={14}/></button>}</div><div className="settings-v27-nav" role="tablist" aria-label="Area pengaturan">{filteredSections.map(s=>{const Icon=s.icon;const active=selectedSection===s.id;return <button type="button" role="tab" aria-selected={active} key={s.id} onClick={()=>selectSection(s.id)} className={clsx("settings-v27-nav-item",active&&"is-active")}><span className="rounded-xl bg-accent/10 p-2 text-accent"><Icon size={14}/></span><span className="min-w-0 text-left"><span className="block truncate text-[11px] font-semibold text-text">{s.label}</span><span className="block truncate text-[9px] text-textMuted">{s.hint}</span></span></button>})}</div></div></section>

    {showSettings&&selectedSection==="appearance"&&<div className="space-y-4"><section className="settings-v27-section"><div><p className="settings-v27-eyebrow">Visual system</p><h2 className="font-display text-2xl text-text">Tampilan & identitas</h2><p className="mt-1 text-xs text-textMuted">Atur wajah Licia tanpa membuat layar penuh menjadi panel kontrol yang berat.</p></div><div className="mt-4 grid gap-3 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-accent/10 p-3 text-accent"><UserRound size={18}/></div><div className="min-w-0"><p className="text-sm font-semibold text-text">Identitas kerja</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Nama dan zona waktu dipakai untuk sapaan, tanggal, agenda, dan konteks AI.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Nama panggilan"><TextInput value={name} onChange={e=>{setName(e.target.value);setSaved(false)}} placeholder="Nama yang ingin dipakai Licia"/></Field><Field label="Zona waktu"><select value={timezone} onChange={e=>{setTimezone(e.target.value);setSaved(false)}} className="min-h-11 w-full rounded-xl border border-border bg-bg px-3 text-sm text-text">{TIMEZONE_OPTIONS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></Field></div></Card><Card className="p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-semibold text-text">Tema & kepadatan</p><p className="mt-1 text-[10px] text-textMuted">Preview berlaku langsung pada antarmuka.</p></div><ThemeToggle onChange={()=>window.dispatchEvent(new CustomEvent("licia:theme-change"))}/></div><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3">{[["compact","Ringkas","Padat"],["comfortable","Nyaman","Seimbang"],["spacious","Lapang","Longgar"]].map(([v,l,d])=><Choice key={v} active={prefs.density===v} title={l} detail={d} onClick={()=>update("density",v)}/>)}</div></Card></div></section>
      <section className="grid gap-3 lg:grid-cols-2"><Card className="p-4 sm:p-5"><div className="flex items-center gap-2"><Palette size={16} className="text-accent"/><div><p className="text-sm font-semibold text-text">Warna aksen</p><p className="text-[9px] text-textMuted">Satu identitas visual di seluruh aplikasi.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{accentPresets.map(x=><button type="button" key={x.hex} title={x.name} onClick={()=>{applyAccent(x.hex);setAccent(x.hex)}} className={clsx("flex h-10 w-10 items-center justify-center rounded-full border-2 transition hover:scale-105",accent.toLowerCase()===x.hex?"border-text scale-105":"border-transparent")} style={{backgroundColor:x.hex}}>{accent.toLowerCase()===x.hex&&<Check size={13} className="text-white"/>}</button>)}</div></Card><Card className="p-4 sm:p-5"><div className="flex items-center gap-2"><Palette size={16} className="text-accentSoft"/><div><p className="text-sm font-semibold text-text">Latar</p><p className="text-[9px] text-textMuted">Latar mengikuti tema aktif.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{(dark?bgPresetsDark:bgPresetsLight).map(x=><button type="button" key={x.hex} onClick={()=>{applyBackground(x.hex);setBackground(x.hex)}} className={clsx("overflow-hidden rounded-xl border text-left",background.toLowerCase()===x.hex?"border-accent":"border-border")}><span className="block h-10" style={{backgroundColor:x.hex}}/><span className="block truncate px-2 py-1.5 text-[8px] font-semibold text-text">{x.name}</span></button>)}</div></Card></section>
      <Card className="p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-semibold text-text">Tipografi</p><p className="text-[9px] text-textMuted">Pilih karakter yang nyaman untuk pembacaan panjang.</p></div><span className="text-[9px] font-semibold text-accent">{fontPresets.find(x=>x.cssVar===font)?.name||"Default"}</span></div><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3">{fontPresets.map(x=><button type="button" key={x.cssVar} onClick={()=>{applyFont(x.cssVar);setFont(x.cssVar)}} className={clsx("rounded-2xl border p-3 text-left",font===x.cssVar?"border-accent/30 bg-accent/5":"border-border bg-bg")}><p className="text-xs font-semibold text-text">{x.name}</p><p className="mt-1 text-[9px] text-textMuted">{x.mood}</p></button>)}</div></Card></div>}

    {showSettings&&selectedSection==="ai"&&<div className="space-y-4"><section className="settings-v27-section"><div><p className="settings-v27-eyebrow">Intelligence</p><h2 className="font-display text-2xl text-text">AI yang punya konteks dan pagar</h2><p className="mt-1 text-xs text-textMuted">Atur seberapa luas Licia membaca Life OS dan kapan ia boleh menyentuh data.</p></div><Card className="mt-4 p-4 sm:p-5"><div className="rounded-2xl border border-accent/15 bg-accent/5 p-4"><div className="flex items-start gap-3"><Sparkles size={17} className="mt-0.5 shrink-0 text-accent"/><div><p className="text-sm font-semibold text-text">Context engine</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Licia dapat menggabungkan tugas, agenda, target, project, finance, health, memory, dan aktivitas yang relevan. Data dikirim secara terpilah melalui konteks yang dibutuhkan, bukan menyalin seluruh database setiap saat.</p></div></div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{[["aiReadAllData","Baca konteks lintas Life OS","Pertanyaan besar dapat memakai konteks beberapa modul."],["aiAutoLink","Hubungkan data otomatis","Tautkan task, project, goal, agenda, note, dan Inbox bila relasinya nyata."],["aiProactive","Saran proaktif","Tampilkan sinyal dan saran tanpa harus meminta satu per satu."],["aiSuggestActions","Saran aksi","Tawarkan operasi yang dapat langsung dijalankan."],["aiConfirmDestructive","Konfirmasi aksi destruktif","Minta persetujuan sebelum penghapusan/perubahan sensitif."],["aiConfirmMassive","Konfirmasi aksi massal","Tampilkan preview satu batch sebelum ratusan perubahan."]].map(([k,l,h])=><Toggle key={k} label={l} hint={h} checked={Boolean(prefs[k as keyof Preferences])} onChange={()=>toggle(k as BooleanPreference)}/>)}</div></Card></section><div className="grid gap-3 lg:grid-cols-2"><Card className="p-4 sm:p-5"><p className="text-sm font-semibold text-text">Gaya kerja AI</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Field label="Mode default"><select value={prefs.defaultAiMode} onChange={e=>update("defaultAiMode",e.target.value)} className="field-v27"><option value="assistant">Assistant</option><option value="planner">Planner</option><option value="reviewer">Reviewer</option><option value="coach">Coach</option></select></Field><Field label="Respons"><select value={prefs.aiResponseStyle} onChange={e=>update("aiResponseStyle",e.target.value)} className="field-v27"><option value="short">Ringkas</option><option value="normal">Normal</option><option value="detailed">Detail</option></select></Field></div></Card><Card className="p-4 sm:p-5"><p className="text-sm font-semibold text-text">Perilaku cerdas</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><Toggle label="Smart suggestions" checked={prefs.smartSuggestions} onChange={()=>toggle("smartSuggestions")}/><Toggle label="Help tips" checked={prefs.showHelpTips} onChange={()=>toggle("showHelpTips")}/></div></Card></div></div>}

    {showSettings&&selectedSection==="workspace"&&<div className="space-y-4"><section className="settings-v27-section"><p className="settings-v27-eyebrow">Workflow</p><h2 className="font-display text-2xl text-text">Workspace & default</h2><p className="mt-1 text-xs text-textMuted">Tetapkan alur awal supaya Licia tidak terasa seperti kumpulan halaman terpisah.</p></section><Card className="p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Halaman awal",<select key="start" value={prefs.startPage} onChange={e=>update("startPage",e.target.value)} className="field-v27"><option value="dashboard">Dashboard</option><option value="today">Hari Ini</option><option value="chat">Chat</option><option value="pulse">Life Pulse</option><option value="command">Life Command</option></select>],
      ["Tampilan tugas",<select key="view" value={prefs.taskView} onChange={e=>update("taskView",e.target.value)} className="field-v27"><option value="list">Daftar</option><option value="board">Papan</option></select>],
      ["Sort tugas",<select key="sort" value={prefs.taskSort} onChange={e=>update("taskSort",e.target.value)} className="field-v27"><option value="next">Terdekat</option><option value="priority">Prioritas</option><option value="created">Terbaru</option></select>],
      ["Kalender",<select key="calendar" value={prefs.calendarView} onChange={e=>update("calendarView",e.target.value)} className="field-v27"><option value="day">Hari</option><option value="month">Bulan</option></select>],
      ["Durasi task",<input key="duration" type="number" min={5} max={480} value={prefs.defaultTaskMinutes} onChange={e=>update("defaultTaskMinutes",Math.max(5,Math.min(480,Number(e.target.value)||25)))} className="field-v27"/>],
      ["Pengingat agenda",<select key="reminder" value={prefs.defaultReminderMinutes} onChange={e=>update("defaultReminderMinutes",Number(e.target.value))} className="field-v27"><option value={0}>Tidak otomatis</option><option value={5}>5 menit sebelumnya</option><option value={10}>10 menit sebelumnya</option><option value={15}>15 menit sebelumnya</option><option value={30}>30 menit sebelumnya</option><option value={60}>1 jam sebelumnya</option><option value={120}>2 jam sebelumnya</option></select>],
      ["Daily Brief",<input key="brief" type="number" min={0} max={23} value={prefs.dailyBriefHour} onChange={e=>update("dailyBriefHour",Math.max(0,Math.min(23,Number(e.target.value)||8)))} className="field-v27"/>],
      ["Weekly Review",<select key="weekly" value={prefs.weeklyReviewDay} onChange={e=>update("weeklyReviewDay",e.target.value)} className="field-v27"><option value="monday">Senin</option><option value="saturday">Sabtu</option><option value="sunday">Minggu</option></select>],
    ].map(([label,control])=><Field key={String(label)} label={String(label)}>{control}</Field>)}</div></Card><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{[["chatEnterToSend","Enter untuk kirim chat"],["autoCompleteFocus","Task selesai setelah Focus"],["showNextMove","Tampilkan Next Move"],["showModuleRail","Tampilkan modul Dashboard"],["confirmDelete","Konfirmasi hapus"],["confirmBulkActions","Konfirmasi bulk action"]].map(([k,l])=><Toggle key={k} label={l} checked={Boolean(prefs[k as keyof Preferences])} onChange={()=>toggle(k as BooleanPreference)}/>)}</div></div>}

    {showSettings&&selectedSection==="experience"&&<div className="space-y-4"><section className="settings-v27-section"><p className="settings-v27-eyebrow">Device & feedback</p><h2 className="font-display text-2xl text-text">Pengalaman penggunaan</h2><p className="mt-1 text-xs text-textMuted">Atur motion, haptic, PWA, Quick Search, dan notifikasi tanpa menyembunyikan kontrol lain.</p></section><Card className="p-4 sm:p-5"><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{[["pageAnimations","Animasi UI"],["motionIntensity","Motion penuh"],["reducedMotion","Reduced motion"],["haptics","Haptic"],["soundFeedback","Sound feedback"],["offlineCapture","Offline capture"],["showQuickSearchMobile","Quick Search HP"],["showDailyIntelligence","Daily Intelligence"],["browserNotifications","Notifikasi browser"]].map(([k,l])=>k==="motionIntensity"?<Toggle key={k} label={l} checked={prefs.motionIntensity!=="off"} onChange={()=>update("motionIntensity",prefs.motionIntensity==="off"?"full":"off")}/>:<Toggle key={k} label={l} checked={Boolean(prefs[k as keyof Preferences])} onChange={()=>toggle(k as BooleanPreference)}/>)}</div></Card><PushNotificationControl/><div className="grid gap-3 sm:grid-cols-2"><Card className="p-4 sm:p-5"><Field label="Interval notifikasi"><select value={prefs.notificationPollMinutes} onChange={e=>update("notificationPollMinutes",Number(e.target.value))} className="field-v27"><option value={1}>1 menit</option><option value={2}>2 menit</option><option value={5}>5 menit</option><option value={10}>10 menit</option></select></Field></Card><Card className="p-4 sm:p-5"><Field label="Jendela pengingat"><select value={prefs.notificationLeadDays} onChange={e=>update("notificationLeadDays",Number(e.target.value))} className="field-v27"><option value={1}>1 hari</option><option value={3}>3 hari</option><option value={7}>7 hari</option><option value={14}>14 hari</option></select></Field></Card></div></div>}

    {showSettings&&selectedSection==="data"&&<div className="space-y-4"><section className="settings-v27-section"><p className="settings-v27-eyebrow">Reliability</p><h2 className="font-display text-2xl text-text">Data, backup & akun</h2><p className="mt-1 text-xs text-textMuted">Satu area khusus untuk keselamatan data dan jejak aksi AI.</p></section><div className="grid gap-3 lg:grid-cols-2"><Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><Download size={18}/></span><div className="min-w-0"><p className="text-sm font-semibold text-text">Arsip HTML</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Dokumen lengkap yang enak dibaca dan dicetak menjadi PDF.</p></div></div><div className="mt-4"><DataExportButton/></div></Card><Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><Database size={18}/></span><div className="min-w-0"><p className="text-sm font-semibold text-text">Backup JSON + restore merge</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Cadangan terstruktur dapat diimpor kembali sebagai merge. Data yang tidak ada di file tidak dihapus.</p></div></div><div className="mt-4"><DataBackupButton/></div></Card></div><div className="grid gap-3 lg:grid-cols-2"><Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><Activity size={18}/></span><div className="min-w-0"><p className="text-sm font-semibold text-text">Health check</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Periksa sesi, database, API, dan latency dari aplikasi.</p></div></div><div className="mt-4"><SoftButton onClick={()=>void checkHealth()} disabled={healthBusy}>{healthBusy?<Sparkles size={14} className="animate-spin"/>:<ShieldCheck size={14}/>} {healthBusy?"Memeriksa…":"Cek sistem"}</SoftButton></div></Card><Card className="p-4 sm:p-5"><div className="flex items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><RotateCcw size={18}/></span><div className="min-w-0"><p className="text-sm font-semibold text-text">AI Action Log</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Lihat operasi AI, batch action, dan pembatalan dari satu tempat.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><a href="/ai-history" className="rounded-xl bg-accent px-3 py-2 text-[10px] font-semibold text-white">Buka riwayat AI</a><a href="/timeline" className="rounded-xl bg-bg px-3 py-2 text-[10px] font-semibold text-textMuted hover:text-accent">Linimasa</a><a href="/reminders" className="rounded-xl bg-bg px-3 py-2 text-[10px] font-semibold text-textMuted hover:text-accent">Pengingat</a><a href="/system" className="rounded-xl bg-bg px-3 py-2 text-[10px] font-semibold text-textMuted hover:text-accent">System Center</a></div></Card></div>
      {health&&<Card className="p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Status",health.ok?"OK":"Gagal"],["Database",health.database?"OK":"Gagal"],["User",health.user?"OK":"—"],["Latency",health.latency_ms?`${health.latency_ms}ms`:"—"]].map(([a,b])=><div key={a} className="rounded-xl bg-bg p-3"><p className="text-[9px] text-textMuted">{a}</p><p className={clsx("mt-1 text-xs font-semibold",b==="OK"?"text-success":"text-text")}>{b}</p></div>)}</div></Card>}
      <Card className="p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="rounded-2xl bg-accent/10 p-3 text-accent"><ShieldCheck size={18}/></span><div><p className="text-sm font-semibold text-text">Sesi perangkat</p><p className="mt-1 text-[10px] leading-relaxed text-textMuted">Keluar akun tersedia di sini maupun melalui menu mobile.</p></div></div><MobileAccountAction/></div></Card>
    </div>}

    {!filteredSections.length&&<Card className="p-8 text-center"><Search size={18} className="mx-auto text-textMuted"/><p className="mt-2 text-sm font-semibold text-text">Area tidak ditemukan</p><p className="mt-1 text-xs text-textMuted">Coba kata seperti AI, tema, notifikasi, atau backup.</p></Card>}
    <div className="rounded-2xl border border-accent/15 bg-accent/5 p-3 sm:p-4"><p className="text-[10px] leading-relaxed text-textMuted">Perubahan tampilan diterapkan langsung. Preferensi akun dan perilaku AI ditulis ke profil setelah menekan <span className="font-semibold text-text">Simpan perubahan</span>.</p></div>
  </div>;
}
