"use client";
import { useEffect, useRef } from "react";
import { Check, X } from "lucide-react";
import { clsx } from "clsx";

export function ActionDialog({open,title,description,children,onClose,onConfirm,confirmLabel="Lanjutkan",cancelLabel="Batal",tone="accent",busy=false}:{open:boolean;title:string;description?:string;children?:React.ReactNode;onClose:()=>void;onConfirm?:()=>void;confirmLabel?:string;cancelLabel?:string;tone?:"accent"|"danger";busy?:boolean}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)onClose();};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[open,onClose,busy]);
 if(!open)return null;
 return <div className="fixed inset-0 z-[240] flex items-end justify-center bg-black/45 p-3 backdrop-blur-[3px] sm:items-center" role="dialog" aria-modal="true" aria-labelledby="licia-dialog-title"><div ref={ref} className="w-full max-w-md overflow-hidden rounded-[1.6rem] border border-border bg-surface shadow-2xl animate-licia-dialog-in"><div className="flex items-start gap-3 px-4 pb-3 pt-4 sm:px-5 sm:pt-5"><div className={clsx("mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl",tone==="danger"?"bg-danger/10 text-danger":"bg-accent/10 text-accent")}>{tone==="danger"?<X size={17}/>:<Check size={17}/>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 id="licia-dialog-title" className="break-words font-display text-lg text-text">{title}</h2><button onClick={onClose} disabled={busy} className="touch-target -mr-2 -mt-2 rounded-xl text-textMuted hover:bg-bg hover:text-text disabled:opacity-50" aria-label="Tutup"><X size={16}/></button></div>{description&&<p className="mt-1 break-words text-xs leading-relaxed text-textMuted">{description}</p>}</div></div>{children&&<div className="px-4 pb-4 sm:px-5">{children}</div>}{onConfirm&&<div className="flex gap-2 border-t border-border bg-bg/45 px-4 py-3 sm:px-5"><button onClick={onClose} disabled={busy} className="min-h-11 flex-1 rounded-xl border border-border bg-surface px-3 text-xs font-semibold text-textMuted hover:text-text">{cancelLabel}</button><button onClick={onConfirm} disabled={busy} className={clsx("min-h-11 flex-1 rounded-xl px-3 text-xs font-semibold text-white",tone==="danger"?"bg-danger":"bg-accent",busy&&"opacity-60")}>{busy?"Memproses…":confirmLabel}</button></div>}</div></div>
}

export function TextPromptDialog({open,title,description,value,onChange,onClose,onSubmit,placeholder="Tulis di sini…",submitLabel="Simpan",multiline=false,busy=false}:{open:boolean;title:string;description?:string;value:string;onChange:(v:string)=>void;onClose:()=>void;onSubmit:()=>void;placeholder?:string;submitLabel?:string;multiline?:boolean;busy?:boolean}){
 return <ActionDialog open={open} title={title} description={description} onClose={onClose} onConfirm={onSubmit} confirmLabel={submitLabel} busy={busy}><label className="block"><span className="sr-only">{title}</span>{multiline?<textarea autoFocus rows={5} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-h-28 w-full resize-none rounded-xl border border-border bg-bg px-3 py-3 text-sm text-text outline-none focus:ring-2 focus:ring-accent/30"/>:<input autoFocus value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-h-11 w-full rounded-xl border border-border bg-bg px-3 py-2.5 text-sm text-text outline-none focus:ring-2 focus:ring-accent/30"/>}</label></ActionDialog>
}
