import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, Droplets, Inbox, Sparkles, Target, Timer, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui";
import { dateStrInTimezone, startOfDayIsoForTimezone, endOfDayIsoForTimezone } from "@/lib/date";
import { previewPlainText } from "@/lib/text";
function minutesLabel(n:number){if(n<60)return `${n} m`;return `${Math.floor(n/60)}j ${n%60?`${n%60}m`:""}`.trim()}
function time(v:string){return v?.slice(0,5)||v}
export default async function TodayPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:profile}=await supabase.from("users").select("display_name,timezone").eq("id",user.id).single();const timezone=profile?.timezone||"Asia/Jakarta";const now=new Date();const today=dateStrInTimezone(now,timezone);const start=startOfDayIsoForTimezone(now,timezone);const end=endOfDayIsoForTimezone(now,timezone);
 const [{data:tasks},{data:agenda},{data:focus},{data:inbox},{data:habits},{data:hydration}]=await Promise.all([
  supabase.from("tasks").select("id,title,status,priority,due_at,estimated_minutes,project_id").eq("user_id",user.id).neq("status","done").order("due_at",{ascending:true,nullsFirst:false}).limit(25),
  supabase.from("schedule_blocks").select("id,title,start_time,end_time,location,description,project_id,task_id").eq("user_id",user.id).order("start_time"),
  supabase.from("pomodoro_sessions").select("focus_minutes,completed,started_at").eq("user_id",user.id).gte("started_at",start).lte("started_at",end).order("started_at",{ascending:false}),
  supabase.from("smart_inbox_items").select("id,content,status,created_at").eq("user_id",user.id).eq("status","open").order("created_at",{ascending:false}).limit(6),
  supabase.from("habit_checkins").select("id,habit_id,checkin_date").eq("user_id",user.id).eq("checkin_date",today),
  supabase.from("hydration_logs").select("amount_ml").eq("user_id",user.id).gte("logged_at",start).lte("logged_at",end),
 ]);
 const openTasks=(tasks||[]) as any[];const agendaRows=(agenda||[]) as any[];const focusRows=focus||[];const inboxRows=inbox||[];const focusMinutes=focusRows.filter((x:any)=>x.completed!==false).reduce((s:number,x:any)=>s+Number(x.focus_minutes||0),0);const water=(hydration||[]).reduce((s:number,x:any)=>s+Number(x.amount_ml||0),0);const overdue=openTasks.filter(t=>t.due_at&&new Date(t.due_at).getTime()<Date.now());const dueSoon=openTasks.filter(t=>t.due_at&&new Date(t.due_at).getTime()<=Date.now()+48*60*60*1000);
 const hour=new Date().toLocaleTimeString("id-ID",{timeZone:timezone,hour:"2-digit",hour12:false});const currentAgenda=agendaRows.find((a:any)=>String(a.start_time)<=hour && hour<String(a.end_time)); const late=Number(hour)>=18;const greeting=late?"Sore yang tenang":"Mari lihat hari ini";
 return <div className="today-page space-y-4 animate-licia-page-in">
  <section className="today-hero rounded-[1.7rem] border border-accent/15 bg-surface p-3.5 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.15em] text-accent">{today}</p><h1 className="mt-1 font-display text-3xl text-text sm:text-4xl">{greeting}{profile?.display_name?`, ${profile.display_name}.`:"."}</h1><p className="mt-1 max-w-2xl text-sm leading-relaxed text-textMuted">Satu layar untuk melihat ritme hari ini: apa yang sudah berjalan, apa yang dekat, dan apa yang bisa kamu lakukan berikutnya.</p></div><Link href="/chat?prompt=Analisis hari saya dan sarankan tiga langkah yang paling relevan berdasarkan kalender, task, inbox, fokus, dan target." className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-4 text-xs font-semibold text-white"><Sparkles size={14}/> Tanya Licia</Link></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-2xl bg-bg p-3"><p className="text-[9px] text-textMuted">Tugas terbuka</p><p className="mt-1 font-display text-2xl text-text">{openTasks.length}</p></div><div className="rounded-2xl bg-danger/5 p-3"><p className="text-[9px] text-textMuted">Terlambat</p><p className="mt-1 font-display text-2xl text-danger">{overdue.length}</p></div><div className="rounded-2xl bg-accent/5 p-3"><p className="text-[9px] text-textMuted">Fokus</p><p className="mt-1 font-display text-2xl text-accent">{minutesLabel(focusMinutes)}</p></div><div className="rounded-2xl bg-accentSoft/5 p-3"><p className="text-[9px] text-textMuted">Hidrasi</p><p className="mt-1 font-display text-2xl text-accentSoft">{water} ml</p></div></div></section>
  {currentAgenda&&<Link href="/calendar" className="today-current-card flex items-center gap-3 rounded-2xl border border-accent/20 bg-accent/5 p-3.5 transition hover:-translate-y-0.5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-accent text-white shadow-sm"><Clock3 size={16}/></span><span className="min-w-0 flex-1"><span className="block text-[9px] font-bold uppercase tracking-[.12em] text-accent">Sedang berlangsung</span><span className="mt-0.5 block break-words text-xs font-semibold text-text">{currentAgenda.title}</span><span className="mt-0.5 block text-[10px] text-textMuted">{time(currentAgenda.start_time)}–{time(currentAgenda.end_time)}{currentAgenda.location?` · ${currentAgenda.location}`:""}</span></span><ArrowRight size={14} className="shrink-0 text-accent"/></Link>}
  <section className="grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><Card className="p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-accent">Ritme hari</p><h2 className="mt-1 font-display text-xl text-text">Agenda yang perlu kamu lihat</h2></div><Link href="/calendar" className="text-textMuted hover:text-accent"><ArrowRight size={14}/></Link></div><div className="mt-4 space-y-2.5">{agendaRows.slice(0,8).map((a:any,i:number)=><Link key={a.id} href="/calendar" className="today-timeline-item group grid grid-cols-[64px_minmax(0,1fr)] gap-3 rounded-2xl border border-border bg-bg p-3 transition hover:border-accent/25"><div className="text-right"><p className="text-xs font-bold tabular-nums text-accent">{time(a.start_time)}</p><p className="mt-0.5 text-[9px] text-textMuted">{time(a.end_time)}</p></div><div className="relative min-w-0 border-l border-border pl-3"><span className="absolute -left-[5px] top-2 h-2 w-2 rounded-full bg-accent ring-4 ring-bg"/><p className="break-words text-sm font-semibold text-text">{a.title}</p><p className="mt-0.5 break-words text-[10px] text-textMuted">{a.location||"Tanpa lokasi"}{a.task_id?" · sudah terhubung task":""}</p></div></Link>)}{!agendaRows.length&&<div className="rounded-2xl border border-dashed border-border p-7 text-center"><CalendarDays size={20} className="mx-auto text-textMuted"/><p className="mt-2 text-sm font-semibold text-text">Hari ini masih kosong</p><p className="mt-1 text-xs text-textMuted">Tambahkan agenda atau gunakan Planner.</p></div>}</div></Card>
   <Card className="p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-success">Langkah berikutnya</p><h2 className="mt-1 font-display text-xl text-text">Sedikit, tapi jelas</h2></div><Timer size={17} className="text-success"/></div><div className="mt-4 space-y-2">{(dueSoon.length?dueSoon:openTasks).slice(0,4).map((t:any)=><Link key={t.id} href={`/focus?task=${t.id}`} className="group block rounded-2xl border border-border bg-bg p-3.5 transition hover:-translate-y-0.5 hover:border-accent/25"><div className="flex items-start justify-between gap-2"><span className={`h-2 w-2 mt-1.5 rounded-full shrink-0 ${t.priority==="high"?"bg-danger":t.priority==="medium"?"bg-accentSoft":"bg-accent"}`}/><span className="min-w-0 flex-1"><b className="block break-words text-xs text-text">{t.title}</b><span className="mt-1 block text-[9px] text-textMuted">{t.due_at?new Date(t.due_at).toLocaleString("id-ID",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Tanpa tenggat"}</span></span><ArrowRight size={11} className="mt-1 text-textMuted transition group-hover:translate-x-1 group-hover:text-accent"/></div></Link>)}{!openTasks.length&&<p className="py-3 text-xs text-textMuted">Tidak ada tugas terbuka. Tangkap sesuatu yang baru?</p>}</div><Link href="/focus" className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-border bg-surface text-xs font-semibold text-textMuted hover:border-accent hover:text-accent"><Timer size={13}/> Buka Fokus</Link></Card>
  </section>
  <section className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><div className="flex items-center gap-2 text-accent"><CheckCircle2 size={15}/><span className="text-[10px] font-bold uppercase tracking-[.12em]">Inbox</span></div><p className="mt-2 font-display text-2xl text-text">{inboxRows.length}</p><p className="text-[10px] text-textMuted">item menunggu dipilah</p><Link href="/inbox" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-accent">Pilah <ArrowRight size={11}/></Link></Card><Card className="p-4"><div className="flex items-center gap-2 text-accentSoft"><Zap size={15}/><span className="text-[10px] font-bold uppercase tracking-[.12em]">Rutinitas</span></div><p className="mt-2 font-display text-2xl text-text">{(habits||[]).length}</p><p className="text-[10px] text-textMuted">check-in hari ini</p><Link href="/habits" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-accent">Buka <ArrowRight size={11}/></Link></Card><Card className="p-4"><div className="flex items-center gap-2 text-accent"><Droplets size={15}/><span className="text-[10px] font-bold uppercase tracking-[.12em]">Sinyal hari</span></div><p className="mt-2 break-words text-sm font-semibold text-text">{overdue.length?`${overdue.length} hal perlu perhatian.`:focusMinutes?`Kamu sudah fokus ${focusMinutes} menit.`:"Hari ini belum punya sinyal kuat."}</p><Link href="/pulse" className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-accent">Life Pulse <ArrowRight size={11}/></Link></Card></section>
  <section className="rounded-2xl border border-border bg-surface px-4 py-3"><div className="flex flex-wrap items-center gap-2 text-[10px] text-textMuted"><Clock3 size={13} className="text-accent"/><span>Semua yang muncul di sini adalah ringkasan. Tekan kartu untuk masuk ke sumber aslinya.</span><span className="ml-auto">{previewPlainText("Life OS",20)}</span></div></section>
 </div>
}
