import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, Inbox, Sparkles, Target, Timer, Wallet } from "lucide-react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { Card, SectionTitle, StatTile } from "@/components/ui";
import { dateStrInTimezone, endOfDayIsoForTimezone, startOfDayIsoForTimezone, startOfWeekIsoForTimezone } from "@/lib/date";
import { LiveClock } from "@/components/LiveClock";
import { timezoneLabel } from "@/lib/time";
import { previewPlainText } from "@/lib/text";

function rupiah(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value)}
function safeMonth(value?:string){return value&&/^\d{4}-\d{2}$/.test(value)?value:null}
function monthBounds(month:string){const [y,m]=month.split("-").map(Number);const start=new Date(Date.UTC(y,m-1,1)).toISOString();const end=new Date(Date.UTC(y,m,1)).toISOString();return{start,end}}
function monthLabel(month:string){return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${month}-01T12:00:00Z`))}
function fmtTime(v:string){return v.slice(0,5)}

export default async function BriefPage({searchParams}:{searchParams?:Promise<{month?:string|string[]}>}){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const params=searchParams?await searchParams:{}; const rawMonth=params.month; const monthParam=Array.isArray(rawMonth)?rawMonth[0]:rawMonth;
 const{data:profile}=await supabase.from("users").select("display_name,timezone").eq("id",user.id).single();const timezone=profile?.timezone??"Asia/Jakarta";const now=new Date();const today=dateStrInTimezone(now,timezone);const dayStart=startOfDayIsoForTimezone(now,timezone);const dayEnd=endOfDayIsoForTimezone(now,timezone);const weekStart=startOfWeekIsoForTimezone(now,timezone);const selectedMonth=safeMonth(monthParam)||today.slice(0,7);const bounds=monthBounds(selectedMonth);
 const [tasks,agenda,focusToday,expensesToday,incomeToday,inboxToday,goals,weekTasks,weekFocus,weekInbox,monthFocus,monthExpenses,monthIncome,monthInbox,monthReading,monthMovement]=await Promise.all([
  supabase.from("tasks").select("id,title,priority,status,due_at").eq("user_id",user.id).neq("status","done").order("due_at",{ascending:true,nullsFirst:false}).limit(12),
  supabase.from("schedule_blocks").select("id,title,start_time,end_time,location").eq("user_id",user.id).eq("block_date",today).order("start_time",{ascending:true}),
  supabase.from("pomodoro_sessions").select("focus_minutes").eq("user_id",user.id).gte("started_at",dayStart).lt("started_at",dayEnd),
  supabase.from("expenses").select("amount").eq("user_id",user.id).gte("occurred_at",dayStart).lt("occurred_at",dayEnd),
  supabase.from("incomes").select("amount").eq("user_id",user.id).gte("occurred_at",dayStart).lt("occurred_at",dayEnd),
  supabase.from("smart_inbox_items").select("id,content,status").eq("user_id",user.id).eq("status","open").order("created_at",{ascending:false}).limit(5),
  supabase.from("goals").select("id,title,progress,target_date,next_step").eq("user_id",user.id).neq("status","completed").order("target_date",{ascending:true,nullsFirst:false}).limit(4),
  supabase.from("tasks").select("status,updated_at").eq("user_id",user.id).gte("updated_at",weekStart).limit(300),
  supabase.from("pomodoro_sessions").select("focus_minutes,started_at").eq("user_id",user.id).gte("started_at",weekStart),
  supabase.from("smart_inbox_items").select("status,created_at").eq("user_id",user.id).gte("created_at",weekStart),
  supabase.from("pomodoro_sessions").select("focus_minutes").eq("user_id",user.id).gte("started_at",bounds.start).lt("started_at",bounds.end),
  supabase.from("expenses").select("amount,category").eq("user_id",user.id).gte("occurred_at",bounds.start).lt("occurred_at",bounds.end),
  supabase.from("incomes").select("amount").eq("user_id",user.id).gte("occurred_at",bounds.start).lt("occurred_at",bounds.end),
  supabase.from("smart_inbox_items").select("status").eq("user_id",user.id).gte("created_at",bounds.start).lt("created_at",bounds.end),
  supabase.from("reading_sessions").select("minutes,pages_read").eq("user_id",user.id).gte("started_at",bounds.start).lt("started_at",bounds.end),
  supabase.from("movement_logs").select("duration_minutes").eq("user_id",user.id).gte("logged_at",bounds.start).lt("logged_at",bounds.end),
 ]);
 const openTasks=tasks.data??[];const urgent=openTasks.find(t=>t.priority==="high"||(t.due_at&&new Date(t.due_at).getTime()<Date.now()));const todayFocus=(focusToday.data??[]).reduce((s,x)=>s+Number(x.focus_minutes),0);const todaySpend=(expensesToday.data??[]).reduce((s,x)=>s+Number(x.amount),0);const todayIncome=(incomeToday.data??[]).reduce((s,x)=>s+Number(x.amount),0);const wDone=(weekTasks.data??[]).filter(x=>x.status==="done").length;const wFocus=(weekFocus.data??[]).reduce((s,x)=>s+Number(x.focus_minutes),0);const mFocus=(monthFocus.data??[]).reduce((s,x)=>s+Number(x.focus_minutes),0);const mSpend=(monthExpenses.data??[]).reduce((s,x)=>s+Number(x.amount),0);const mIncome=(monthIncome.data??[]).reduce((s,x)=>s+Number(x.amount),0);const mInbox=monthInbox.data??[];const mReading=(monthReading.data??[]).reduce((s,x)=>s+Number(x.minutes),0);const mPages=(monthReading.data??[]).reduce((s,x)=>s+Number(x.pages_read||0),0);const mMove=(monthMovement.data??[]).reduce((s,x)=>s+Number(x.duration_minutes),0);const mNew=mInbox.filter(x=>x.status==="open").length;const wInbox=weekInbox.data??[];const wInboxProcessed=wInbox.filter(x=>x.status==="processed").length;const mProcessed=mInbox.filter(x=>x.status==="processed").length;const displayDate=new Intl.DateTimeFormat("id-ID",{timeZone:timezone,weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now);
 return <div className="space-y-7 animate-licia-in">
  <header className="relative overflow-hidden rounded-3xl border border-border bg-surface p-5 sm:p-7"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-accent/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><Sparkles size={14}/> HARI INI · RINGKASAN + REVIEW</p><h1 className="font-display text-3xl text-text sm:text-4xl">Halo, {profile?.display_name||"kamu"}.</h1><p className="mt-2 text-sm leading-relaxed text-textMuted">{displayDate}. Satu tempat untuk melihat hari ini, ritme 7 hari terakhir, dan konteks bulanan.</p></div><LiveClock timezone={timezone}/></div></header>
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-6"><StatTile label="Tugas terbuka" value={String(openTasks.length)} icon={CheckCircle2} tone="accent"/><StatTile label="Agenda hari ini" value={String(agenda.data?.length??0)} icon={CalendarDays}/><StatTile label="Fokus hari ini" value={`${todayFocus} mnt`} icon={Timer} tone="accent"/><StatTile label="Arus hari ini" value={rupiah(todayIncome-todaySpend)} hint={`+${rupiah(todayIncome)} / -${rupiah(todaySpend)}`} icon={Wallet} tone={todayIncome>=todaySpend?"success":"danger"}/><StatTile label="Inbox baru" value={String(inboxToday.data?.length??0)} icon={Inbox}/><StatTile label="Target aktif" value={String(goals.data?.length??0)} icon={Target}/></div>
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
   <Card><SectionTitle>Perhatian utama</SectionTitle>{urgent?<div className="rounded-2xl border border-accent/20 bg-accent/5 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-accent">Tindakan berikutnya</p><p className="mt-1 text-base font-semibold text-text">{urgent.title}</p><p className="mt-1 text-xs text-textMuted">{urgent.due_at?`Deadline ${new Intl.DateTimeFormat("id-ID",{timeZone:timezone,weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(urgent.due_at))}`:"Tidak ada deadline"}</p><Link href="/tasks" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-accent">Kelola tugas <ArrowRight size={12}/></Link></div>:<p className="text-sm text-textMuted">Tidak ada tugas mendesak. Pilih satu hal yang paling bernilai untuk hari ini.</p>}<div className="mt-4 space-y-2">{(goals.data??[]).slice(0,3).map(g=><div key={g.id} className="rounded-xl bg-bg p-3"><div className="flex items-center justify-between gap-2"><span className="truncate text-xs font-semibold text-text">{g.title}</span><span className="text-[11px] text-accent">{Number(g.progress||0)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-surface"><div className="h-full rounded-full bg-accent transition-all" style={{width:`${Math.max(0,Math.min(100,Number(g.progress||0)))}%`}}/></div>{g.next_step&&<p className="mt-2 line-clamp-1 text-[11px] text-textMuted">Berikutnya: {g.next_step}</p>}</div>)}</div></Card>
   <Card><SectionTitle action={<Link href="/inbox" className="text-xs font-semibold text-textMuted hover:text-accent">Inbox <ArrowRight size={12} className="inline"/></Link>}>Agenda + capture</SectionTitle>{agenda.data?.length?<div className="space-y-2">{agenda.data.slice(0,6).map(a=><div key={a.id} className="flex gap-3 rounded-xl bg-bg p-3"><div className="w-14 shrink-0 text-center"><p className="text-xs font-bold text-accent">{fmtTime(a.start_time)}</p><p className="text-[10px] text-textMuted">{fmtTime(a.end_time)}</p></div><div className="min-w-0"><p className="truncate text-sm font-semibold text-text">{a.title}</p>{a.location&&<p className="mt-0.5 truncate text-[11px] text-textMuted">{a.location}</p>}</div></div>)}</div>:<p className="text-sm text-textMuted">Belum ada agenda. Smart Inbox bisa dipakai untuk menangkap hal spontan.</p>}{(inboxToday.data??[]).slice(0,2).map(i=><div key={i.id} className="mt-2 rounded-xl border border-dashed border-border p-3"><p className="line-clamp-2 text-xs text-text">{previewPlainText(i.content, 140)}</p></div>)}</Card>
  </div>
  <Card><SectionTitle>Review 7 hari terakhir</SectionTitle><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Tugas selesai</p><p className="mt-1 font-display text-2xl text-success">{wDone}</p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Fokus</p><p className="mt-1 font-display text-2xl text-accent">{wFocus}<span className="text-sm text-textMuted"> mnt</span></p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Inbox diproses</p><p className="mt-1 font-display text-2xl text-text">{wInboxProcessed}</p></div><div className="rounded-xl bg-bg p-4"><p className="text-xs text-textMuted">Agenda hari ini</p><p className="mt-1 font-display text-2xl text-text">{agenda.data?.length??0}</p></div></div><p className="mt-4 text-xs leading-relaxed text-textMuted">Angka ini bukan skor. Gunakan sebagai bahan refleksi: apa yang memang bergerak, apa yang tertunda, dan apa yang perlu dibuat lebih sederhana minggu berikutnya.</p></Card>
  <div className="flex flex-col gap-3 rounded-2xl border border-border bg-surface p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-text">Review bulanan · {monthLabel(selectedMonth)}</p><p className="mt-1 text-xs text-textMuted">Filter bulan ini untuk melihat akumulasi aktivitas, bukan hanya snapshot hari ini.</p></div><form method="get" className="flex w-full gap-2 sm:w-auto"><input type="month" name="month" defaultValue={selectedMonth} className="min-h-11 min-w-0 flex-1 rounded-xl border border-border bg-bg px-3 text-sm text-text outline-none focus:ring-2 focus:ring-accent/40 sm:w-44"/><button className="min-h-11 rounded-xl bg-accent px-4 text-xs font-semibold text-white">Terapkan</button></form></div>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><StatTile label="Fokus bulan" value={`${mFocus} mnt`} icon={Clock3} tone="accent"/><StatTile label="Arus bersih" value={rupiah(mIncome-mSpend)} icon={Wallet} tone={mIncome>=mSpend?"success":"danger"}/><StatTile label="Inbox diproses" value={String(mProcessed)} hint={`${mNew} masih baru`} icon={Inbox}/><StatTile label="Membaca + gerak" value={`${mReading+mMove} mnt`} hint={`${mPages} halaman dibaca`} icon={BookOpen}/></div>
  <Card className="border-accent/20 bg-accent/5"><div className="flex flex-wrap gap-2"><Link href="/timeline" className="rounded-xl bg-surface px-3 py-2 text-xs font-semibold text-textMuted hover:text-accent">Linimasa <ArrowRight size={12} className="inline"/></Link><Link href="/analytics" className="rounded-xl bg-surface px-3 py-2 text-xs font-semibold text-textMuted hover:text-accent">Analitik Pribadi <ArrowRight size={12} className="inline"/></Link><Link href="/planner" className="rounded-xl bg-surface px-3 py-2 text-xs font-semibold text-textMuted hover:text-accent">Perencana AI <ArrowRight size={12} className="inline"/></Link></div></Card>
 </div>;
}
