import fs from "node:fs";
import path from "node:path";
const root = process.cwd();
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");
const must = (cond, msg) => { if (!cond) throw new Error(msg); console.log(`PASS ${msg}`); };
const pkg = JSON.parse(read("package.json"));
const batch = read("app/api/ai/batch/route.ts");
const tools = read("lib/ai/tools.ts");
const chat = read("app/api/chat/route.ts");
const date = read("lib/date.ts");
const lock = JSON.parse(read("package-lock.json"));
must(pkg.version === "0.35.2", "package version 0.35.2");
must(lock.version === "0.35.2" && lock.packages?.[""]?.version === "0.35.2", "lock version 0.35.2");
must(batch.includes("pending: true") && batch.includes("failed_details"), "all-failed batch remains pending and reports per-action errors");
must(batch.includes("applied_with_errors"), "partial batch gets applied_with_errors status");
must(tools.includes("Tanggal agenda harus berupa YYYY-MM-DD"), "schedule import validates concrete dates");
must(tools.includes("optionalColumnsMissing") && tools.includes("minimalPayload"), "schedule creation falls back when optional columns are missing");
must(chat.includes("scheduleImageRequest") && chat.includes("tidak mencantumkan tanggal/tahun"), "schedule image without concrete date asks before mutation");
must(chat.includes("ATURAN TAMPIL WAKTU") && chat.includes("13:50, bukan 06:50"), "AI timezone display guard is present");
must(chat.includes("decorateTemporalToolResult"), "chat decorates reminder timestamps with local time");
must(tools.includes("remind_at_local") && tools.includes("timezone_label"), "reminder tool results expose local display fields");
must(date.includes("formatTimeInTimezone") && date.includes("formatDateTimeInTimezone"), "timezone formatting helpers exist");
console.log("V35.2 tests passed");
