"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Camera, Check, FileText, Inbox, Loader2, Mic, MicOff, Plus, Sparkles, StickyNote, Wand2, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, PrimaryButton, SoftButton, notifyToast } from "@/components/ui";
import { enqueueMutation, requestBackgroundSync, getDeviceId } from "@/lib/pwa/offlineQueue";
import { fileToCompressedDataUrl } from "@/lib/image";

type CaptureMode="inbox"|"task"|"note";
type RecognitionLike={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;start:()=>void;stop:()=>void;abort:()=>void;onresult:(e:any)=>void;onerror:(e:any)=>void;onend:()=>void;onstart:()=>void};
type CaptureCard=[string,LucideIcon,string,string];

export default function CaptureStudioPage(){
 const router=useRouter();
 const[text,setText]=useState("");const[mode,setMode]=useState<CaptureMode>("inbox");const[busy,setBusy]=useState(false);const[voice,setVoice]=useState(false);const[voiceStatus,setVoiceStatus]=useState("Siap mendengarkan");const[voiceSupported,setVoiceSupported]=useState(false);const[preview,setPreview]=useState<string|null>(null);const[imageData,setImageData]=useState<string|null>(null);
 const fileRef=useRef<HTMLInputElement>(null);const recognitionRef=useRef<RecognitionLike|null>(null);const voiceBaseRef=useRef("");
 useEffect(()=>{const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;setVoiceSupported(Boolean(Speech));return()=>{try{recognitionRef.current?.abort()}catch{}}},[]);
 async function startVoice(){
  const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
  if(!Speech){notifyToast({title:"Voice input tidak tersedia",message:"Gunakan Chrome/Edge terbaru pada HTTPS untuk Web Speech.",tone:"info"});return;}
  if(voice){try{recognitionRef.current?.stop()}catch{}return;}
  try{
   if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());}
  }catch(error){notifyToast({title:"Mikrofon belum diizinkan",message:error instanceof DOMException&&error.name==="NotAllowedError"?"Izinkan mikrofon untuk licia.site lalu tekan Voice lagi.":"Browser tidak memberi akses mikrofon.",tone:"error"});return;}
  const rec=Speech() as RecognitionLike;recognitionRef.current=rec;voiceBaseRef.current=text.trim();rec.lang="id-ID";rec.interimResults=true;rec.continuous=false;rec.maxAlternatives=1;
  rec.onstart=()=>{setVoice(true);setVoiceStatus("Mendengarkan…");};
  rec.onresult=(event:any)=>{let finalText="";let interimText="";for(let i=event.resultIndex;i<event.results.length;i+=1){const t=String(event.results[i]?.[0]?.transcript||"");if(event.results[i]?.isFinal)finalText+=t;else interimText+=t;}const committed=[voiceBaseRef.current,finalText].filter(Boolean).join(voiceBaseRef.current&&finalText?" ":"").trim();setText(interimText?`${committed}${committed?" ":""}${interimText}`.trim():committed);};
  rec.onerror=(event:any)=>{const code=String(event?.error||"");setVoice(false);setVoiceStatus(code==="not-allowed"?"Izin mikrofon ditolak.":code==="network"?"Layanan speech butuh koneksi internet.":code==="no-speech"?"Tidak ada suara terdeteksi.":"Voice berhenti karena browser mengalami kendala.");};
  rec.onend=()=>{setVoice(false);setVoiceStatus("Siap mendengarkan");};
  try{rec.start();}catch{setVoice(false);setVoiceStatus("Voice belum bisa dimulai. Coba tekan sekali lagi.");}
 }
 function stopVoice(){try{recognitionRef.current?.stop()}catch{}setVoice(false);setVoiceStatus("Siap mendengarkan");}
 async function pickImage(file:File){if(!file.type.startsWith("image/"))return;try{const data=await fileToCompressedDataUrl(file,1600,.72);setImageData(data);setPreview(data);notifyToast({title:"Gambar siap",message:"Lampiran dapat diteruskan ke Chat untuk dibaca Licia.",tone:"success"})}catch{notifyToast({title:"Gambar belum bisa diproses",tone:"error"})}}
 async function sendToLicia(){if(!imageData&&!text.trim())return;setBusy(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text.trim()||"Pahami gambar ini dan tentukan tindakan yang paling tepat.",imageDataUrl:imageData})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||"Licia belum bisa memproses capture.");notifyToast({title:"Dikirim ke Licia",message:"Capture diproses dengan konteks vision dan tool Life OS.",tone:"success"});router.push(`/chat?prompt=${encodeURIComponent(text.trim()||"Pahami gambar ini")}`)}catch(error){notifyToast({title:"AI belum memproses capture",message:error instanceof Error?error.message:"Terjadi kesalahan.",tone:"error"})}finally{setBusy(false)}}
 async function capture(){const content=text.trim();if(!content||busy)return;setBusy(true);try{const{data:{user}}=await createClient().auth.getUser();if(!user)throw new Error("Belum masuk.");const entityType=mode==="inbox"?"inbox":mode;const payload=mode==="inbox"?{content,kind:"inbox",status:"open"}:mode==="task"?{title:content,status:"todo",priority:"medium"}:{title:content.slice(0,80),content};if(!navigator.onLine){const queued=await enqueueMutation({userId:user.id,deviceId:getDeviceId(),entityType,operation:"create",payload,conflictStrategy:"server"});if(!queued)throw new Error("Antrean offline penuh.");await requestBackgroundSync();notifyToast({title:"Disimpan di perangkat",message:"Perubahan akan disinkronkan saat online.",tone:"success"});}else{const response=await fetch("/api/sync/mutation",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({mutationId:crypto.randomUUID(),deviceId:getDeviceId(),entityType,operation:"create",payload,conflictStrategy:"server"})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||"Capture belum tersimpan.");notifyToast({title:mode==="inbox"?"Masuk ke Smart Inbox":mode==="task"?"Tugas dibuat":"Catatan dibuat",message:content.slice(0,140),tone:"success"});}setText("");setImageData(null);setPreview(null);router.refresh();}catch(error){notifyToast({title:"Capture belum tersimpan",message:error instanceof Error?error.message:"Terjadi kesalahan.",tone:"error"})}finally{setBusy(false)}}
 const cards:CaptureCard[]=[["/chat?prompt=Analisis capture saya dan sarankan bentuk data yang paling tepat.",Sparkles,"Pilah dengan Licia","Biarkan AI menentukan bentuk data yang paling relevan."],["/inbox",Inbox,"Rapikan di Inbox","Tangkap cepat sekarang, rapikan saat punya waktu."],["/guide",Wand2,"Pelajari alurnya","Dari capture ke action tanpa perlu mengingat semua menu."]];
 return <div className="capture-page space-y-4 animate-licia-page-in">
  <section className="capture-hero rounded-[1.7rem] border border-accent/15 bg-surface p-4 sm:p-5"><div className="flex items-start gap-3"><div className="rounded-2xl bg-accent/10 p-3 text-accent"><Camera size={18}/></div><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-accent">Capture Studio</p><h1 className="mt-1 break-words font-display text-2xl text-text sm:text-3xl">Tangkap dulu. Rapikan nanti.</h1><p className="mt-1 max-w-2xl text-xs leading-relaxed text-textMuted">Teks, suara, atau gambar masuk ke Life OS tanpa memaksamu memilih struktur dari awal.</p></div><Link href="/inbox" className="hidden min-h-10 shrink-0 items-center gap-1.5 rounded-xl border border-border bg-bg px-3 text-[10px] font-semibold text-textMuted hover:border-accent/30 hover:text-accent sm:inline-flex">Inbox <ArrowRight size={12}/></Link></div></section>
  <Card className="capture-composer overflow-hidden p-0"><div className="grid grid-cols-3 border-b border-border">{([["inbox",Inbox,"Inbox","Belum jelas"],["task",FileText,"Tugas","Harus dikerjakan"],["note",StickyNote,"Catatan","Perlu disimpan"]] as const).map(([value,Icon,title,desc])=><button key={value} onClick={()=>setMode(value)} className={clsx("capture-mode min-w-0 px-2.5 py-3 text-left transition sm:px-4",mode===value?"bg-accent/5 text-accent":"text-textMuted hover:bg-bg")}><div className="flex items-center justify-center gap-2 sm:justify-start"><span className={clsx("rounded-lg p-1.5",mode===value?"bg-accent/10":"bg-bg")}><Icon size={15}/></span><span className="min-w-0"><b className="block truncate text-[10px] sm:text-xs">{title}</b><span className="hidden text-[9px] sm:block">{desc}</span></span></div></button>)}</div><div className="p-3 sm:p-4"><textarea value={text} onChange={e=>setText(e.target.value)} rows={6} placeholder={mode==="inbox"?"Tulis apa pun yang sedang ada di kepala…":mode==="task"?"Tulis pekerjaan secara konkret…":"Tulis informasi yang ingin kamu simpan…"} className="capture-textarea min-h-40 w-full resize-none rounded-2xl border border-border bg-bg px-4 py-4 text-sm leading-relaxed text-text outline-none focus:ring-2 focus:ring-accent/30"/>{preview&&<div className="relative mt-3 overflow-hidden rounded-2xl border border-border bg-bg p-2"><button onClick={()=>{setPreview(null);setImageData(null)}} className="touch-target absolute right-2 top-2 z-10 rounded-xl bg-surface/90 text-textMuted shadow hover:text-danger" aria-label="Hapus gambar"><X size={14}/></button><img src={preview} alt="Pratinjau capture" className="max-h-64 w-full rounded-xl object-contain"/></div>}<div className="mt-3 flex flex-wrap items-center gap-2"><PrimaryButton onClick={()=>void capture()} disabled={!text.trim()||busy} className="min-h-11">{busy?<Loader2 size={15} className="animate-spin"/>:<Plus size={15}/>} {busy?"Menyimpan…":mode==="inbox"?"Tangkap":"Simpan"}</PrimaryButton><SoftButton onClick={()=>void startVoice()} disabled={!voiceSupported&& !voice}>{voice?<MicOff size={15}/>:<Mic size={15}/>} {voice?"Hentikan":"Voice input"}</SoftButton>{(imageData||text.trim())&&<SoftButton onClick={()=>void sendToLicia()} disabled={busy}><Sparkles size={15}/> Kirim ke Licia</SoftButton>}<button onClick={()=>fileRef.current?.click()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border bg-surface px-3.5 text-xs font-semibold text-textMuted hover:border-accent/30 hover:text-accent"><Camera size={15}/> Gambar</button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)void pickImage(f)}}/><span className={clsx("w-full break-words text-[9px] sm:w-auto sm:ml-auto",voice?"text-accent":"text-textMuted")}>{voiceStatus}</span></div></div></Card>
  <section className="grid gap-2 sm:grid-cols-3">{cards.map(([href,Icon,title,desc])=>{const I=Icon;return <Link key={href} href={href} className="group rounded-2xl border border-border bg-surface p-3.5 transition hover:-translate-y-0.5 hover:border-accent/25"><div className="flex items-center gap-2 text-accent"><I size={15}/><span className="text-xs font-semibold">{title}</span><ArrowRight size={11} className="ml-auto transition group-hover:translate-x-1"/></div><p className="mt-1.5 text-[10px] leading-relaxed text-textMuted">{desc}</p></Link>})}</section>
 </div>
}
