"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarClock, CircleDollarSign, Plus, ReceiptText, Trash2 } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";
import { previewPlainText } from "@/lib/text";

type Sub={id:string;name:string;amount:number;billing_cycle:"monthly"|"yearly";next_billing_date:string|null;active:boolean;reminder_days:number|null;service_url:string|null;notes:string|null};
function rupiah(n:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function daysUntil(v:string|null){if(!v)return null;return Math.ceil((new Date(`${v}T12:00:00`).getTime()-Date.now())/86400000)}
export default function SubscriptionsPage(){const supabase=createClient();const[rows,setRows]=useState<Sub[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState({name:"",amount:"",cycle:"monthly" as "monthly"|"yearly",next:"",url:"",notes:"",reminder:"3"});
 async function load(){const{data}=await supabase.from("subscriptions").select("id,name,amount,billing_cycle,next_billing_date,active,reminder_days,service_url,notes").order("next_billing_date",{ascending:true,nullsFirst:false});setRows((data as Sub[])??[])}useEffect(()=>{load()},[]);async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}async function add(){if(!form.name.trim()||!form.amount)return;await supabase.from("subscriptions").insert({user_id:await uid(),name:form.name.trim(),amount:Number(form.amount),billing_cycle:form.cycle,next_billing_date:form.next||null,service_url:form.url.trim()||null,notes:form.notes.trim()||null,reminder_days:Number(form.reminder)||3,active:true});setForm({name:"",amount:"",cycle:"monthly",next:"",url:"",notes:"",reminder:"3"});setOpen(false);load()}async function toggle(r:Sub){await supabase.from("subscriptions").update({active:!r.active}).eq("id",r.id);load()}async function remove(id:string){await supabase.from("subscriptions").delete().eq("id",id);load()}
 const active=rows.filter(r=>r.active);const monthly=active.reduce((s,r)=>s+Number(r.amount)/(r.billing_cycle==="yearly"?12:1),0);const annual=active.reduce((s,r)=>s+Number(r.amount)*(r.billing_cycle==="yearly"?1:12),0);const next=useMemo(()=>active.filter(r=>r.next_billing_date).sort((a,b)=>new Date(a.next_billing_date!).getTime()-new Date(b.next_billing_date!).getTime()).slice(0,5),[active]);
 return <div className="space-y-7 animate-licia-in"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><ReceiptText size={14}/> RECURRING MONEY</p><h1 className="font-display text-3xl text-text">Langganan</h1><p className="mt-1 max-w-2xl text-sm leading-relaxed text-textMuted">Bukan sekadar daftar layanan. Lihat biaya bulanan, paparan tahunan, dan kapan tagihan berikutnya datang.</p></div><PrimaryButton onClick={()=>setOpen(v=>!v)}><Plus size={16}/> Langganan baru</PrimaryButton></header>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card className="p-4"><p className="text-xs text-textMuted">Aktif</p><p className="mt-1 font-display text-2xl text-accent">{active.length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Burn bulanan</p><p className="mt-1 font-display text-xl text-text">{rupiah(Math.round(monthly))}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Paparan tahunan</p><p className="mt-1 font-display text-xl text-text">{rupiah(Math.round(annual))}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Tagihan terdekat</p><p className="mt-1 text-sm font-semibold text-text">{next[0]?.next_billing_date?new Date(`${next[0].next_billing_date}T12:00:00`).toLocaleDateString("id-ID",{day:"numeric",month:"short"}):"—"}</p></Card></div>
 {open&&<Card className="border-accent/20 bg-accent/5"><SectionTitle>Tambahkan layanan</SectionTitle><div className="grid gap-2 sm:grid-cols-2"><TextInput value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama layanan"/><TextInput type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Biaya"/><select value={form.cycle} onChange={e=>setForm({...form,cycle:e.target.value as any})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"><option value="monthly">Bulanan</option><option value="yearly">Tahunan</option></select><input type="date" value={form.next} onChange={e=>setForm({...form,next:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"/><TextInput value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="URL layanan (opsional)"/><TextInput type="number" value={form.reminder} onChange={e=>setForm({...form,reminder:e.target.value})} placeholder="Ingatkan H-3"/><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="sm:col-span-2 min-h-20 resize-none rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:ring-2 focus:ring-accent/30" placeholder="Catatan pembatalan, paket, atau detail penting…"/></div><div className="mt-3 flex justify-end"><PrimaryButton onClick={add}>Simpan langganan</PrimaryButton></div></Card>}
 <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card><SectionTitle>Jadwal tagihan</SectionTitle>{next.length?<div className="space-y-2">{next.map(r=>{const d=daysUntil(r.next_billing_date);return <div key={r.id} className="flex gap-3 rounded-xl bg-bg p-3"><div className={clsx("rounded-xl p-2",d!==null&&d<=7?"bg-danger/10 text-danger":"bg-accent/10 text-accent")}><CalendarClock size={16}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold text-text">{r.name}</p><span className="shrink-0 text-sm font-semibold text-text">{rupiah(Number(r.amount))}</span></div><p className="mt-1 text-xs text-textMuted">{new Date(`${r.next_billing_date}T12:00:00`).toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long"})}{d!==null?` · ${d<0?"terlewat":d===0?"hari ini":`H-${d}`}`:""}</p></div></div>})}</div>:<EmptyState title="Belum ada tanggal tagihan" description="Tambahkan tanggal billing supaya Licia bisa menunjukkan apa yang sebentar lagi jatuh tempo."/>}</Card><Card><SectionTitle>Semua layanan</SectionTitle>{active.length?<div className="space-y-2">{active.map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl border border-border p-3"><div className="rounded-xl bg-accent/10 p-2 text-accent"><CircleDollarSign size={15}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-text">{r.name}</p><p className="text-[10px] text-textMuted">{rupiah(Number(r.amount))} · {r.billing_cycle==="yearly"?"per tahun":"per bulan"}</p>{r.notes&&<p className="mt-1 line-clamp-2 text-[10px] text-textMuted">{previewPlainText(r.notes,160)}</p>}</div><button onClick={()=>toggle(r)} className="rounded-lg px-2 py-1.5 text-[10px] text-textMuted hover:text-accent">Nonaktifkan</button><button onClick={()=>remove(r.id)} className="rounded-lg p-2 text-textMuted hover:text-danger"><Trash2 size={14}/></button></div>)}</div>:<EmptyState title="Belum ada langganan" description="Mulai dari layanan yang benar-benar dibayar rutin setiap bulan atau tahun."/>}</Card></div>
 </div>
}
