"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BookOpen, Check, Copy, FileText, Lightbulb, Pin, PinOff, Plus, Search, Sparkles, Trash2, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";
import { MarkdownLite } from "@/components/chat/MarkdownLite";

type Note={id:string;title:string|null;content:string;tags:string[];created_at:string;updated_at:string|null;pinned:boolean;color:string|null;project_id:string|null;area_id:string|null};
type Project={id:string;name:string}; type Area={id:string;name:string};
const colorClass:Record<string,string>={blue:"border-accent/25 bg-accent/5",gold:"border-accentSoft/25 bg-accentSoft/5",green:"border-success/25 bg-success/5",default:"border-border bg-surface"};
type NoteTemplate = { id:string; label:string; icon:LucideIcon; title:string; content:string };
const templates:NoteTemplate[]=[
 {id:"idea",label:"Ide",icon:Lightbulb,title:"Ide baru",content:"## Inti ide\n\n**Masalah:**\n\n**Gagasan:**\n\n**Langkah berikutnya:**\n"},
 {id:"study",label:"Belajar",icon:BookOpen,title:"Catatan belajar",content:"## Materi\n\n**Konsep penting:**\n\n**Contoh:**\n\n**Yang masih membingungkan:**\n\n**Next step:**\n"},
 {id:"meeting",label:"Agenda",icon:Sparkles,title:"Catatan agenda",content:"## Tujuan\n\n**Poin utama:**\n\n**Keputusan:**\n\n**Tindak lanjut:**\n"}
];
export default function NotesPage(){
 const supabase=createClient(); const[notes,setNotes]=useState<Note[]>([]);const[projects,setProjects]=useState<Project[]>([]);const[areas,setAreas]=useState<Area[]>([]);const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const[filter,setFilter]=useState<"all"|"pinned">("all");const[editing,setEditing]=useState<string|null>(null);const[edit,setEdit]=useState({title:"",content:"",tags:""});const[form,setForm]=useState({title:"",content:"",tags:"",color:"default",project_id:"",area_id:""});
 async function load(){const[{data:n},{data:p},{data:a}]=await Promise.all([supabase.from("brain_dump_notes").select("id,title,content,tags,created_at,updated_at,pinned,color,project_id,area_id").order("pinned",{ascending:false}).order("updated_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}),supabase.from("projects").select("id,name").eq("status","active").order("name"),supabase.from("areas").select("id,name").order("name")]);setNotes((n as Note[])??[]);setProjects((p as Project[])??[]);setAreas((a as Area[])??[])}
 useEffect(()=>{load()},[]);async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}
 async function add(){if(!form.content.trim())return;await supabase.from("brain_dump_notes").insert({user_id:await uid(),title:form.title.trim()||null,content:form.content.trim(),tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),color:form.color,project_id:form.project_id||null,area_id:form.area_id||null});setForm({title:"",content:"",tags:"",color:"default",project_id:"",area_id:""});setOpen(false);load()}
 function useTemplate(t:typeof templates[number]){setForm(f=>({...f,title:t.title,content:t.content}));setOpen(true)}
 async function save(id:string){await supabase.from("brain_dump_notes").update({title:edit.title.trim()||null,content:edit.content.trim(),tags:edit.tags.split(",").map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()}).eq("id",id);setEditing(null);load()}
 async function pin(n:Note){await supabase.from("brain_dump_notes").update({pinned:!n.pinned,updated_at:new Date().toISOString()}).eq("id",n.id);load()}
 async function remove(id:string){await supabase.from("brain_dump_notes").delete().eq("id",id);load()}
 async function openChat(n:Note){window.location.href=`/chat?prompt=${encodeURIComponent(`Bantu saya merapikan catatan berikut tanpa mengubah maksudnya:\n\n${n.content}`)}`}
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return notes.filter(n=>(filter==="all"||n.pinned)&&(!q||`${n.title||""} ${n.content} ${(n.tags||[]).join(" ")}`.toLowerCase().includes(q)))},[notes,query,filter]);
 const words=(s:string)=>s.trim()?s.trim().split(/\s+/).length:0;
 return <div className="space-y-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><FileText size={14}/> Capture · Think · Reuse</p><h1 className="font-display text-3xl text-text">Catatan</h1><p className="mt-1 max-w-3xl text-sm text-textMuted">Simpan ide, ringkasan belajar, atau catatan kerja tanpa memaksa semuanya menjadi tugas. Hubungkan ke project atau area bila konteksnya penting.</p></div><PrimaryButton onClick={()=>setOpen(v=>!v)}><Plus size={16}/> Catatan baru</PrimaryButton></header>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card className="p-4"><p className="text-xs text-textMuted">Semua catatan</p><p className="mt-1 font-display text-2xl text-text">{notes.length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Disorot</p><p className="mt-1 font-display text-2xl text-accent">{notes.filter(n=>n.pinned).length}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Kata tersimpan</p><p className="mt-1 font-display text-2xl text-text">{notes.reduce((s,n)=>s+words(n.content),0)}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Terhubung project</p><p className="mt-1 font-display text-2xl text-success">{notes.filter(n=>n.project_id).length}</p></Card></div>
  <Card><div className="flex flex-wrap gap-2">{templates.map(t=>{const Icon=t.icon;return <button key={t.id} onClick={()=>useTemplate(t)} className="inline-flex items-center gap-1.5 rounded-xl border border-border bg-bg px-3 py-2 text-xs font-semibold text-textMuted hover:border-accent hover:text-accent"><Icon size={13}/>{t.label}</button>})}<span className="self-center text-[10px] text-textMuted">Template hanya titik awal; isi bebas kamu ubah.</span></div></Card>
  {open&&<Card className="border-accent/20 bg-accent/5"><SectionTitle>Tulis catatan</SectionTitle><div className="grid gap-2 sm:grid-cols-2"><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Judul (opsional)"/><TextInput value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="Tag, dipisahkan koma"/><select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"><option value="">Tanpa project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"><option value="">Tanpa area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="mt-2 flex gap-2">{Object.keys(colorClass).map(c=><button key={c} onClick={()=>setForm({...form,color:c})} className={clsx("h-7 w-7 rounded-full border",form.color===c?"ring-2 ring-accent ring-offset-2 ring-offset-surface":"",c==="blue"?"bg-accent":c==="gold"?"bg-accentSoft":c==="green"?"bg-success":"bg-bg")} aria-label={`Warna ${c}`}/>)}</div><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} rows={9} placeholder="Tulis apa pun yang perlu diingat…" className="mt-3 w-full resize-none rounded-xl border border-border bg-surface px-4 py-3 text-sm leading-relaxed text-text outline-none focus:ring-2 focus:ring-accent"/><div className="mt-3 flex justify-end"><PrimaryButton onClick={add} disabled={!form.content.trim()}><Plus size={15}/> Simpan</PrimaryButton></div></Card>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex gap-1 rounded-xl border border-border bg-surface p-1"><button onClick={()=>setFilter("all")} className={clsx("rounded-lg px-3 py-2 text-xs font-semibold",filter==="all"?"bg-accent text-white":"text-textMuted")}>Semua</button><button onClick={()=>setFilter("pinned")} className={clsx("rounded-lg px-3 py-2 text-xs font-semibold",filter==="pinned"?"bg-accent text-white":"text-textMuted")}>Disorot</button></div><div className="relative min-w-0 flex-1"><Search size={15} className="pointer-events-none absolute left-3 top-3 text-textMuted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari judul, isi, atau tag…" className="w-full rounded-xl border border-border bg-surface py-2.5 pl-9 pr-4 text-sm text-text outline-none focus:ring-2 focus:ring-accent"/></div></div>
  <SectionTitle action={<span className="text-[10px] text-textMuted">{visible.length} catatan terlihat</span>}>Koleksi catatan</SectionTitle>
  {!visible.length?<EmptyState title="Belum ada catatan yang cocok" description="Buat catatan baru atau ubah kata pencarian."/>:<div className="grid gap-3 md:grid-cols-2">{visible.map(n=>{const isEditing=editing===n.id;return <Card key={n.id} className={clsx("min-w-0 overflow-hidden p-4",colorClass[n.color||"default"])}>{isEditing?<div className="space-y-2"><TextInput value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} placeholder="Judul"/><textarea value={edit.content} onChange={e=>setEdit({...edit,content:e.target.value})} rows={9} className="w-full resize-none rounded-xl border border-border bg-bg px-3 py-2 text-sm text-text outline-none focus:ring-2 focus:ring-accent"/><TextInput value={edit.tags} onChange={e=>setEdit({...edit,tags:e.target.value})} placeholder="Tag"/><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="rounded-lg p-2 text-textMuted"><X size={15}/></button><button onClick={()=>save(n.id)} className="rounded-lg p-2 text-accent"><Check size={15}/></button></div></div>:<><div className="flex items-start gap-3"><div className="rounded-xl bg-bg p-2 text-accent"><FileText size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5"><span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">{n.pinned?"Disorot":"Catatan"}</span>{(n.tags||[]).slice(0,3).map(t=><span key={t} className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">#{t}</span>)}</div><p className="mt-2 break-words font-display text-lg text-text">{n.title||"Tanpa judul"}</p><div className="mt-1 line-clamp-6 text-sm leading-relaxed text-text"><MarkdownLite text={n.content}/></div><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[10px] text-textMuted"><span>{words(n.content)} kata</span>{n.project_id&&<Link href="/projects" className="text-accent hover:underline">Project terhubung</Link>}{n.area_id&&<span>Area terhubung</span>}</div></div><div className="flex shrink-0 gap-1"><button onClick={()=>pin(n)} className={clsx("rounded-lg p-2",n.pinned?"text-accent":"text-textMuted hover:text-accent")} title="Sorot"><>{n.pinned?<Pin size={14}/>:<PinOff size={14}/>}</></button><button onClick={()=>openChat(n)} className="rounded-lg p-2 text-textMuted hover:text-accent" title="Rapikan dengan Licia"><Sparkles size={14}/></button><button onClick={()=>navigator.clipboard?.writeText(n.content)} className="rounded-lg p-2 text-textMuted hover:text-accent" title="Salin"><Copy size={14}/></button><button onClick={()=>{setEditing(n.id);setEdit({title:n.title||"",content:n.content,tags:(n.tags||[]).join(", ")})}} className="rounded-lg p-2 text-textMuted hover:text-accent" title="Edit"><FileText size={14}/></button><button onClick={()=>remove(n.id)} className="rounded-lg p-2 text-textMuted hover:text-danger" title="Hapus"><Trash2 size={14}/></button></div></div></>}</Card>})}</div>}
 </div>
}
