"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, CheckCircle2, Clock3, Search, ShieldCheck, Sparkles, Trash2, Undo2, WandSparkles } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, SoftButton, notifyToast } from "@/components/ui";

type Action={id:string;tool_name:string;label:string;operation:string;table_name:string;record_ids:unknown;batch_id:string|null;undoable:boolean;undone_at:string|null;created_at:string};
const opLabel:Record<string,string>={create:"Membuat",update:"Mengubah",delete:"Menghapus"};
function actionTone(operation:string){return operation==="delete"?"danger":operation==="update"?"accentSoft":"success"}
function timeLabel(v:string){return new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}

export default function AIHistoryPage(){
 const supabase=createClient();const[actions,setActions]=useState<Action[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[operation,setOperation]=useState("all");const[undoing,setUndoing]=useState<string|null>(null);
 async function load(){setLoading(true);const{data}=await supabase.from("ai_action_history").select("id,tool_name,label,operation,table_name,record_ids,batch_id,undoable,undone_at,created_at").order("created_at",{ascending:false}).limit(160);setActions((data as Action[])||[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function undo(id:string){if(undoing)return;if(!window.confirm("Batalkan aksi AI ini? Untuk aksi batch, seluruh batch yang belum dibatalkan akan dicoba dipulihkan."))return;setUndoing(id);try{const res=await fetch("/api/ai/undo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionId:id})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Undo gagal.");notifyToast({title:"Aksi dibatalkan",message:"Perubahan yang didukung sudah dipulihkan.",tone:"success"});await load()}catch(error){notifyToast({title:"Undo gagal",message:error instanceof Error?error.message:"Coba lagi.",tone:"error"})}finally{setUndoing(null)}}
 const filtered=useMemo(()=>actions.filter(a=>{const q=query.trim().toLowerCase();const qOk=!q||`${a.label} ${a.tool_name} ${a.table_name}`.toLowerCase().includes(q);return qOk&&(operation==="all"||a.operation===operation)}),[actions,query,operation]);
 const stats={total:actions.length,undoable:actions.filter(a=>a.undoable&&!a.undone_at).length,batches:new Set(actions.map(a=>a.batch_id).filter(Boolean)).size,undone:actions.filter(a=>a.undone_at).length};
 return <div className="ai-history-v27 space-y-5 animate-licia-page-in">
   <header className="ai-history-v27-hero relative overflow-hidden rounded-[2rem] border border-accent/15 bg-surface p-5 shadow-sm sm:p-7"><div className="absolute -right-20 -top-20 h-60 w-60 rounded-full bg-accent/10 blur-3xl"/><div className="relative"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><Link href="/settings" className="inline-flex items-center gap-1 text-[10px] font-semibold text-accent"><ArrowLeft size={12}/> Pengaturan</Link><p className="mt-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.17em] text-accent"><WandSparkles size={13}/> AI transparency</p><h1 className="mt-1 break-words font-display text-3xl text-text sm:text-4xl">AI Action Log</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-textMuted">Jejak operasi yang benar-benar dilakukan Licia. Batch action terlihat sebagai bagian dari satu proses dan aksi yang mendukung snapshot dapat dibatalkan.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-2xl border border-border bg-bg/75 p-3"><p className="text-[9px] text-textMuted">Aksi</p><p className="mt-1 font-display text-xl text-text">{stats.total}</p></div><div className="rounded-2xl border border-border bg-bg/75 p-3"><p className="text-[9px] text-textMuted">Undo</p><p className="mt-1 font-display text-xl text-accent">{stats.undoable}</p></div><div className="rounded-2xl border border-border bg-bg/75 p-3"><p className="text-[9px] text-textMuted">Batch</p><p className="mt-1 font-display text-xl text-text">{stats.batches}</p></div><div className="rounded-2xl border border-border bg-bg/75 p-3"><p className="text-[9px] text-textMuted">Dibatalkan</p><p className="mt-1 font-display text-xl text-success">{stats.undone}</p></div></div></div></div></header>
   <section className="flex flex-col gap-2 rounded-2xl border border-border bg-surface p-3 sm:flex-row"><div className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-border bg-bg px-3"><Search size={14} className="shrink-0 text-textMuted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari aksi, tool, atau tabel…" className="min-w-0 flex-1 bg-transparent py-2.5 text-xs text-text outline-none"/></div><div className="grid grid-cols-4 gap-1.5 sm:flex sm:flex-wrap">{[["all","Semua"],["create","Buat"],["update","Ubah"],["delete","Hapus"]].map(([v,l])=><button key={v} type="button" onClick={()=>setOperation(v)} className={clsx("rounded-xl border px-3 py-2 text-[10px] font-semibold",operation===v?"border-accent/25 bg-accent/5 text-accent":"border-border bg-bg text-textMuted")}>{l}</button>)}</div></section>
   {loading?<Card className="p-5"><div className="space-y-2"><div className="h-16 animate-licia-shimmer rounded-xl bg-bg"/><div className="h-16 animate-licia-shimmer rounded-xl bg-bg"/><div className="h-16 animate-licia-shimmer rounded-xl bg-bg"/></div></Card>:!filtered.length?<EmptyState title="Belum ada aksi yang cocok" description="Aksi yang dilakukan melalui Chat atau Life Command akan muncul di sini ketika tersimpan di AI Action History." action={<Link href="/command" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-accent px-3 text-xs font-semibold text-white"><Sparkles size={13}/> Buka Life Command</Link>}/>:<div className="space-y-2.5">{filtered.map((a,index)=>{const tone=actionTone(a.operation);const count=Array.isArray(a.record_ids)?a.record_ids.length:0;return <Card key={a.id} className={clsx("ai-history-v27-item p-3.5 sm:p-4",index<5&&"animate-licia-slide-in")}><div className="flex items-start gap-3"><span className={clsx("mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl",tone==="danger"?"bg-danger/10 text-danger":tone==="accentSoft"?"bg-accentSoft/10 text-accentSoft":"bg-success/10 text-success")}>{a.operation==="delete"?<Trash2 size={15}/>:a.operation==="update"?<Activity size={15}/>:<CheckCircle2 size={15}/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><p className="break-words text-sm font-semibold text-text">{a.label}</p><span className="rounded-full bg-bg px-2 py-1 text-[8px] font-semibold text-textMuted">{opLabel[a.operation]||a.operation}</span>{a.batch_id&&<span className="rounded-full bg-accent/5 px-2 py-1 text-[8px] font-semibold text-accent">Batch</span>}{a.undone_at&&<span className="rounded-full bg-success/10 px-2 py-1 text-[8px] font-semibold text-success">Dibatalkan</span>}</div><p className="mt-1 break-words text-[10px] text-textMuted">{a.tool_name} · {a.table_name} · {count||1} record · {timeLabel(a.created_at)}</p></div>{a.undoable&&!a.undone_at&&<button type="button" onClick={()=>void undo(a.id)} disabled={undoing===a.id} className="touch-target shrink-0 rounded-xl border border-accent/20 bg-accent/5 px-2.5 text-[9px] font-semibold text-accent disabled:opacity-50">{undoing===a.id?<Clock3 size={13} className="animate-spin"/>:<Undo2 size={13}/>} <span className="hidden sm:inline">Undo</span></button>}</div></Card>})}</div>}
   <Card className="border-accent/15 bg-accent/5 p-4"><div className="flex items-start gap-3"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-accent"/><div><p className="text-sm font-semibold text-text">Kenapa fitur ini penting</p><p className="mt-1 text-xs leading-relaxed text-textMuted">AI boleh membantu, tetapi setiap mutasi harus tetap dapat ditelusuri. Snapshot, batch identifier, dan undo membuat perubahan lebih mudah diaudit tanpa menyembunyikan apa yang terjadi.</p></div></div></Card>
 </div>;
}
