"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, Check, Clock3, Flame, Plus, Star, Trash2 } from "lucide-react";
import { clsx } from "clsx";
import { createClient } from "@/lib/supabase/client";
import { Card, EmptyState, PrimaryButton, SectionTitle, TextInput } from "@/components/ui";
import { previewPlainText } from "@/lib/text";

type Book={id:string;title:string;author:string|null;genre:string|null;status:"want_to_read"|"reading"|"finished";progress:number;rating:number|null;notes:string|null;total_pages:number|null;current_page:number|null;format:string|null;started_at:string|null;finished_at:string|null;last_read_at:string|null;takeaways:string|null};
type Session={id:string;reading_id:string;minutes:number;pages_read:number;note:string|null;started_at:string};
const labels={want_to_read:"Antrian",reading:"Sedang dibaca",finished:"Selesai"};
function dayKey(d:Date){return d.toISOString().slice(0,10)}
function dateText(v:string){return new Date(v).toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric"})}
export default function ReadingPage(){
 const supabase=createClient();const[books,setBooks]=useState<Book[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[form,setForm]=useState({title:"",author:"",genre:"",pages:"",format:"digital"});const[open,setOpen]=useState(false);const[tab,setTab]=useState<"all"|Book["status"]>("all");const[expanded,setExpanded]=useState<string|null>(null);const[draft,setDraft]=useState<Record<string,{notes:string;takeaways:string}>>({});const[sessionForm,setSessionForm]=useState({minutes:"20",pages:"0",note:""});
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[{data:b},{data:s}]=await Promise.all([supabase.from("reading_logs").select("id,title,author,genre,status,progress,rating,notes,total_pages,current_page,format,started_at,finished_at,last_read_at,takeaways").order("updated_at",{ascending:false}),supabase.from("reading_sessions").select("id,reading_id,minutes,pages_read,note,started_at").eq("user_id",user.id).order("started_at",{ascending:false}).limit(500)]);setBooks((b as Book[])??[]);setSessions((s as Session[])??[])}
 useEffect(()=>{load()},[]);async function uid(){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Belum masuk");return user.id}
 async function add(){if(!form.title.trim())return;await supabase.from("reading_logs").insert({user_id:await uid(),title:form.title.trim(),author:form.author.trim()||null,genre:form.genre.trim()||null,total_pages:form.pages?Number(form.pages):null,format:form.format,status:"want_to_read",progress:0,current_page:0});setForm({title:"",author:"",genre:"",pages:"",format:"digital"});setOpen(false);load()}
 async function updateProgress(b:Book,p:number){const status=p>=100?"finished":p>0?"reading":"want_to_read";const now=new Date().toISOString();const patch:any={progress:p,status,current_page:b.total_pages?Math.round(Number(b.total_pages)*p/100):b.current_page,last_read_at:now};if(status==="reading"&&!b.started_at)patch.started_at=now;if(status==="finished"&&!b.finished_at)patch.finished_at=now;await supabase.from("reading_logs").update({...patch,updated_at:now}).eq("id",b.id);load()}
 async function pages(b:Book,p:string){const n=Math.max(0,Number(p)||0);const pct=b.total_pages?Math.min(100,Math.round(n/Number(b.total_pages)*100)):b.progress;await updateProgress(b,pct);await supabase.from("reading_logs").update({current_page:n,updated_at:new Date().toISOString()}).eq("id",b.id);load()}
 async function rating(id:string,n:number){await supabase.from("reading_logs").update({rating:n,updated_at:new Date().toISOString()}).eq("id",id);load()}
 async function saveText(id:string){const d=draft[id];if(!d)return;await supabase.from("reading_logs").update({notes:d.notes.trim()||null,takeaways:d.takeaways.trim()||null,updated_at:new Date().toISOString()}).eq("id",id);load()}
 async function addSession(b:Book){const minutes=Math.max(1,Math.min(1440,Number(sessionForm.minutes)||20));const pagesRead=Math.max(0,Number(sessionForm.pages)||0);const now=new Date().toISOString();await supabase.from("reading_sessions").insert({user_id:await uid(),reading_id:b.id,minutes,pages_read:pagesRead,note:sessionForm.note.trim()||null,started_at:now});const nextPage=Math.min(Number(b.total_pages||Number.MAX_SAFE_INTEGER),Number(b.current_page||0)+pagesRead);const pct=b.total_pages?Math.min(100,Math.round(nextPage/Number(b.total_pages)*100)):b.progress;const status=pct>=100?"finished":pct>0?"reading":b.status;const patch:any={current_page:nextPage,progress:pct,status,last_read_at:now,updated_at:now};if(status==="reading"&&!b.started_at)patch.started_at=now;if(status==="finished"&&!b.finished_at)patch.finished_at=now;await supabase.from("reading_logs").update(patch).eq("id",b.id);setSessionForm({minutes:"20",pages:"0",note:""});load()}
 async function del(id:string){await supabase.from("reading_logs").delete().eq("id",id);load()}
 const visible=tab==="all"?books:books.filter(b=>b.status===tab);const finished=books.filter(b=>b.status==="finished").length;const inProgress=books.filter(b=>b.status==="reading").length;const avg=books.length?Math.round(books.reduce((s,b)=>s+b.progress,0)/books.length):0;const sessionWeek=sessions.filter(s=>new Date(s.started_at).getTime()>=Date.now()-7*86400000);const minutesWeek=sessionWeek.reduce((s,x)=>s+x.minutes,0);const pagesWeek=sessionWeek.reduce((s,x)=>s+x.pages_read,0);const readingDays=new Set(sessions.map(s=>dayKey(new Date(s.started_at))));let streak=0;const cursor=new Date();while(readingDays.has(dayKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}const genres=useMemo(()=>Object.entries(books.reduce((m,b)=>{if(b.genre)m[b.genre]=(m[b.genre]||0)+1;return m},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]).slice(0,4),[books]);
 return <div className="space-y-7">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-accent"><BookOpen size={14}/> Read · Capture · Remember</p><h1 className="font-display text-3xl text-text">Bacaan</h1><p className="mt-1 max-w-3xl text-sm text-textMuted">Bukan hanya daftar buku. Catat sesi membaca, halaman yang berpindah, insight, dan ritme supaya bacaan bisa terhubung ke Learning & Skills.</p></div><PrimaryButton onClick={()=>setOpen(v=>!v)}><Plus size={16}/> Tambah bacaan</PrimaryButton></header>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Card className="p-4"><p className="text-xs text-textMuted">Sedang dibaca</p><p className="mt-1 font-display text-2xl text-accent">{inProgress}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Selesai</p><p className="mt-1 font-display text-2xl text-success">{finished}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Fokus baca 7 hari</p><p className="mt-1 font-display text-2xl text-text">{minutesWeek}<span className="text-sm text-textMuted">m</span></p></Card><Card className="p-4"><p className="text-xs text-textMuted">Halaman 7 hari</p><p className="mt-1 font-display text-2xl text-text">{pagesWeek}</p></Card><Card className="p-4"><p className="text-xs text-textMuted">Streak baca</p><p className="mt-1 flex items-center gap-1 font-display text-2xl text-text"><Flame size={18} className="text-accentSoft"/>{streak}d</p></Card></div>
  {open&&<Card className="border-accent/20 bg-accent/5"><SectionTitle>Tambahkan bacaan</SectionTitle><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><TextInput value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Judul"/><TextInput value={form.author} onChange={e=>setForm({...form,author:e.target.value})} placeholder="Penulis"/><TextInput value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})} placeholder="Genre"/><TextInput type="number" min="1" value={form.pages} onChange={e=>setForm({...form,pages:e.target.value})} placeholder="Total halaman"/><select value={form.format} onChange={e=>setForm({...form,format:e.target.value})} className="min-h-11 rounded-xl border border-border bg-surface px-3 text-sm text-text"><option value="digital">Digital</option><option value="physical">Fisik</option><option value="audio">Audio</option></select></div><div className="mt-3 flex justify-end"><PrimaryButton onClick={add}><Plus size={15}/> Simpan</PrimaryButton></div></Card>}
  <Card className="border-border/70 bg-surfaceRaised/40"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-text">Sesi membaca</p><p className="mt-1 text-xs text-textMuted">Setiap sesi tersimpan sebagai jejak waktu. Ini membuat progress bacaan dan Learning & Skills lebih bisa dipercaya.</p></div><div className="flex items-center gap-2 text-xs text-textMuted"><Clock3 size={14}/> {sessions.length} sesi tercatat</div></div></Card>
  <div className="flex gap-1 overflow-x-auto rounded-xl border border-border bg-surface p-1 no-scrollbar">{([['all','Semua'],['want_to_read','Antrian'],['reading','Sedang dibaca'],['finished','Selesai']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={clsx("shrink-0 rounded-lg px-3 py-2 text-xs font-semibold",tab===k?"bg-accent text-white":"text-textMuted")}>{l}</button>)}</div>
  {!visible.length?<EmptyState title="Belum ada bacaan" description="Tambahkan buku, dokumentasi, manga, atau materi yang memang ingin kamu pelajari."/>:<div className="grid gap-3 md:grid-cols-2">{visible.map(b=>{const ex=expanded===b.id;const pg=b.current_page||0;const bookSessions=sessions.filter(s=>s.reading_id===b.id);const totalSessionMins=bookSessions.reduce((s,x)=>s+x.minutes,0);const totalPages=bookSessions.reduce((s,x)=>s+x.pages_read,0);return <Card key={b.id} className="min-w-0 overflow-hidden p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-accent/10 p-2.5 text-accent"><BookOpen size={17}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-1.5"><span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">{labels[b.status]}</span>{b.genre&&<span className="rounded-full bg-bg px-2 py-1 text-[10px] text-textMuted">{b.genre}</span>}</div><p className="mt-2 break-words font-display text-lg text-text">{b.title}</p><p className="mt-0.5 truncate text-xs text-textMuted">{b.author||"Penulis tidak dicatat"}</p></div><button onClick={()=>del(b.id)} className="shrink-0 p-2 text-textMuted hover:text-danger"><Trash2 size={14}/></button></div>
    <div className="mt-4 flex items-center justify-between text-xs"><span className="text-textMuted">{b.total_pages?`${pg}/${b.total_pages} halaman`:`${b.progress}%`}</span><span className="font-semibold text-accent">{b.progress}%</span></div><div className="mt-1.5 h-2 rounded-full bg-bg"><div className="h-full rounded-full bg-accent transition-all" style={{width:`${b.progress}%`}}/></div>
    <div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl bg-bg p-2.5 text-center"><p className="text-sm font-semibold text-text">{totalSessionMins}m</p><p className="text-[10px] text-textMuted">waktu total</p></div><div className="rounded-xl bg-bg p-2.5 text-center"><p className="text-sm font-semibold text-text">{totalPages}</p><p className="text-[10px] text-textMuted">halaman sesi</p></div><div className="rounded-xl bg-bg p-2.5 text-center"><p className="text-sm font-semibold text-text">{bookSessions.length}</p><p className="text-[10px] text-textMuted">sesi</p></div></div>
    <div className="mt-3 flex items-center gap-2"><input type="range" min={0} max={100} value={b.progress} onChange={e=>updateProgress(b,Number(e.target.value))} className="min-w-0 flex-1 accent-accent"/><input type="number" min={0} value={pg} onChange={e=>pages(b,e.target.value)} className="w-20 rounded-lg border border-border bg-bg px-2 py-1.5 text-right text-xs text-text"/></div>
    <button onClick={()=>{setExpanded(ex?null:b.id);if(!ex){setDraft({...draft,[b.id]:{notes:b.notes||"",takeaways:b.takeaways||""}});setSessionForm({minutes:"20",pages:"0",note:""})}}} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-semibold text-textMuted hover:border-accent hover:text-accent">{ex?"Tutup detail":"Buka sesi & insight"}</button>
    {ex&&<div className="mt-3 space-y-3 border-t border-border pt-3"><div className="rounded-xl bg-bg p-3"><p className="text-[10px] uppercase tracking-wider text-accent">Catat sesi sekarang</p><div className="mt-2 grid gap-2 sm:grid-cols-3"><TextInput type="number" min="1" value={sessionForm.minutes} onChange={e=>setSessionForm({...sessionForm,minutes:e.target.value})} placeholder="Menit"/><TextInput type="number" min="0" value={sessionForm.pages} onChange={e=>setSessionForm({...sessionForm,pages:e.target.value})} placeholder="Halaman"/><TextInput value={sessionForm.note} onChange={e=>setSessionForm({...sessionForm,note:e.target.value})} placeholder="Catatan sesi (opsional)"/></div><div className="mt-2 flex flex-wrap gap-1.5">{[15,30,45,60].map(n=><button key={n} onClick={()=>setSessionForm({...sessionForm,minutes:String(n)})} className="rounded-full border border-border px-2.5 py-1 text-[10px] text-textMuted hover:border-accent hover:text-accent">{n}m</button>)}<button onClick={()=>addSession(b)} className="ml-auto rounded-xl bg-accent px-3 py-2 text-[11px] font-semibold text-white">Simpan sesi</button></div></div><div><p className="mb-1 text-[10px] uppercase tracking-wider text-textMuted">Rating pribadi</p><div className="flex gap-1">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>rating(b.id,n)}><Star size={18} className={n<=(b.rating||0)?"fill-accentSoft text-accentSoft":"text-textMuted"}/></button>)}</div></div><TextInput value={draft[b.id]?.notes||""} onChange={e=>setDraft({...draft,[b.id]:{...draft[b.id],notes:e.target.value}})} placeholder="Catatan pribadi…"/><textarea value={draft[b.id]?.takeaways||""} onChange={e=>setDraft({...draft,[b.id]:{...draft[b.id],takeaways:e.target.value}})} rows={3} placeholder="Apa yang benar-benar kamu bawa dari bacaan ini?" className="w-full resize-none rounded-xl border border-border bg-bg px-3 py-2 text-sm text-text outline-none focus:ring-2 focus:ring-accent"/><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-[10px] text-textMuted">{b.last_read_at?`Terakhir dibaca ${dateText(b.last_read_at)}`:"Belum ada sesi membaca"}</p><button onClick={()=>saveText(b.id)} className="rounded-xl bg-accent px-3 py-2 text-xs font-semibold text-white">Simpan insight</button></div><div className="border-t border-border pt-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-textMuted">Sesi terakhir</p>{bookSessions.slice(0,3).map(s=><div key={s.id} className="mt-2 flex items-start gap-2 rounded-lg bg-bg p-2 text-[10px]"><CalendarDays size={12} className="mt-0.5 shrink-0 text-accent"/><span className="min-w-0 flex-1 text-textMuted">{dateText(s.started_at)} · {s.minutes} menit · {s.pages_read} halaman{s.note?` · ${previewPlainText(s.note,140)}`:""}</span></div>)}</div></div>}
  </Card>})}</div>}
  <Card><SectionTitle>Genre yang paling sering muncul</SectionTitle>{genres.length?<div className="flex flex-wrap gap-2">{genres.map(([g,n])=><span key={g} className="rounded-full bg-bg px-3 py-1.5 text-xs text-text">{g} · {n}</span>)}</div>:<p className="text-sm text-textMuted">Belum cukup data untuk melihat pola genre.</p>}</Card>
 </div>
}
